### ISSUE TITLE
[Bug]: Unable to get brains on local

### ISSUE THREAD

**Issue by B0rrA** [StanGirard/quivr#1261]
### What happened?

A bug happened! After updated to latest version a cannot get my brains. 

URL:
http://localhost:5050/brains/
method:
GET
status:
500 Internal Server Error

### Relevant log output

```bash
backend-core  | 2023-09-26 00:21:04,395 [INFO] repository.brain.get_default_user_brain: Default brain response: 3fde9136-e452-4e79-b172-532371ed2ffe
backend-core  | 2023-09-26 00:21:04,395 [INFO] repository.brain.get_default_user_brain: Default brain id: 3fde9136-e452-4e79-b172-532371ed2ffe
backend-core  | INFO:     10.20.10.59:56486 - "GET /user HTTP/1.1" 200 OK
backend-core  | INFO:     10.20.10.59:56487 - "GET /brains/3fde9136-e452-4e79-b172-532371ed2ffe/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
backend-core  |     solved_result = await solve_dependencies(
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
backend-core  |     solved = await call(**sub_values)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/authorizations/brain_authorization.py", line 26, in wrapper
backend-core  |     validate_brain_authorization(
backend-core  |   File "/code/routes/authorizations/brain_authorization.py", line 52, in validate_brain_authorization
backend-core  |     user_brain = get_brain_for_user(user_id, brain_id)
backend-core  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_brain_for_user.py", line 8, in get_brain_for_user
backend-core  |     return supabase_db.get_brain_for_user(user_id, brain_id)  # type: ignore
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 108, in get_brain_for_user
backend-core  |     return MinimalBrainEntity(
backend-core  |            ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for MinimalBrainEntity
backend-core  | status
backend-core  |   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by StanGirard** [comment]
@B0rrA run the migration script :)

**Comment by schoenix** [comment]
I got a similar error. It is a fresh install. I am using podman on a manjaro linux, instead of docker on ubuntu, but this shouldn't matter for this particular problem.

**Comment by B0rrA** [comment]
@StanGirard i found the error. The get_user_brains method search in the brains table but using `id` not `brain_id`. This maybe is because some migration file change the table column name or the method is just wrong. If is the second case, let me know to make the PR

```
def get_user_brains(self, user_id) -> list[MinimalBrainEntity]:
        response = (
            self.db.from_("brains_users")
            .select("id:brain_id, rights, brains (brain_id, name, status)")  # HERE i change 'id' for 'brain_id'
            .filter("user_id", "eq", user_id)
            .execute()
        )
        user_brains: list[MinimalBrainEntity] = []
        for item in response.data:
            user_brains.append(
                MinimalBrainEntity(
                    id=item["brains"]["brain_id"],  # HERE i change 'id' for 'brain_id'
                    name=item["brains"]["name"],
                    rights=item["rights"],
                    status=item["brains"]["status"],
                )
            )
            user_brains[-1].rights = item["rights"]
        return user_brains
```

**Comment by B0rrA** [comment]
The method is located in backend/models/databases/supabase/brains.py

**Comment by schoenix** [comment]
Do you have a fix for it?

**Comment by B0rrA** [comment]
I have created a PR just in case @schoenix https://github.com/StanGirard/quivr/pull/1272

**Comment by lugfug** [comment]
Bump
