### ISSUE TITLE
[Bug]: Can't add brain

### ISSUE THREAD

**Issue by sphinxcoldhand** [StanGirard/quivr#1283]
### What happened?

I'm running Quivr on Ubuntu 22.04 on a VM with IP 192.168.1.12.
I acces Quivr from 192.168.1.11
When trying to Add New Brain I get an error message (bottom-right corner on browser, red background):
message "Network Error", name "AxiosError" etc

### Relevant log output

```bash
backend-core  | INFO:     192.168.1.11:37300 - "GET /brains/ HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.11:37304 - "GET /prompts HTTP/1.1" 200 OK
backend-core  | 2023-09-28 17:38:48,876 [INFO] repository.brain.get_default_user_brain: Default brain response: None
backend-core  | INFO:     192.168.1.11:37316 - "GET /brains/default/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/brain_routes.py", line 81, in get_default_brain_endpoint
backend-core  |     brain = get_default_user_brain_or_create_new(current_user)
backend-core  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_default_user_brain_or_create_new.py", line 14, in get_default_user_brain_or_create_new
backend-core  |     default_brain = create_brain(CreateBrainProperties())
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/create_brain.py", line 8, in create_brain
backend-core  |     return supabase_db.create_brain(brain)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 56, in create_brain
backend-core  |     return BrainEntity(**response.data[0])
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainEntity
backend-core  | last_update
backend-core  |   field required (type=value_error.missing)
backend-core  | INFO:     192.168.1.11:37300 - "GET /chat HTTP/1.1" 200 OK
backend-core  | 2023-09-28 17:38:50,695 [INFO] repository.brain.get_default_user_brain: Default brain response: None
backend-core  | INFO:     192.168.1.11:37326 - "GET /user HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.11:37332 - "GET /user/identity HTTP/1.1" 200 OK
backend-core  | 2023-09-28 17:38:54,633 [INFO] repository.brain.get_default_user_brain: Default brain response: None
backend-core  | INFO:     192.168.1.11:37332 - "GET /user HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.11:37332 - "GET /prompts HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.11:54214 - "POST /brains/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/brain_routes.py", line 143, in create_brain_endpoint
backend-core  |     new_brain = create_brain(
backend-core  |                 ^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/create_brain.py", line 8, in create_brain
backend-core  |     return supabase_db.create_brain(brain)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 56, in create_brain
backend-core  |     return BrainEntity(**response.data[0])
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainEntity
backend-core  | last_update
backend-core  |   field required (type=value_error.missing)
```

**Comment by sphinxcoldhand** [comment]
The issue of the last_update field not being provided when creating a new brain should be considered a bug and solved with an update.
