### ISSUE TITLE
[Bug]: why the knowledge was empty

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#1287]
### What happened?

after update from 0.0.7x to 0.0.85 and add_knowledge_tables. the knowledge tab always said "Oh No, Your Brain is empty." And the knowledge table in Supabase was also empty. But I checked from quivr-0.0.76 the knowledge was there.

**Comment by georgeqin96** [comment]
INFO:     172.18.0.1:35394 - "GET /knowledge?brain_id=596d4494-9d3f-40fd-bdd2-47cc020c6a04 HTTP/1.1" 200 OK
2023-09-29 21:55:34 INFO:     172.18.0.1:56274 - "GET /user/identity HTTP/1.1" 200 OK
2023-09-29 21:55:38 INFO:     172.18.0.1:56264 - "GET /brains/596d4494-9d3f-40fd-bdd2-47cc020c6a04/ HTTP/1.1" 200 OK
2023-09-29 21:55:42 --- Logging error ---
2023-09-29 21:55:42 Traceback (most recent call last):
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
2023-09-29 21:55:42     msg = self.format(record)
2023-09-29 21:55:42           ^^^^^^^^^^^^^^^^^^^
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
2023-09-29 21:55:42     return fmt.format(record)
2023-09-29 21:55:42            ^^^^^^^^^^^^^^^^^^
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
2023-09-29 21:55:42     record.message = record.getMessage()
2023-09-29 21:55:42                      ^^^^^^^^^^^^^^^^^^^
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
2023-09-29 21:55:42     msg = msg % self.args
2023-09-29 21:55:42           ~~~~^~~~~~~~~~~
2023-09-29 21:55:42 TypeError: not all arguments converted during string formatting
2023-09-29 21:55:42 Call stack:
2023-09-29 21:55:42   File "<string>", line 1, in <module>
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
2023-09-29 21:55:42     exitcode = _main(fd, parent_sentinel)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 135, in _main
2023-09-29 21:55:42     return self._bootstrap(parent_sentinel)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2023-09-29 21:55:42     self.run()
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2023-09-29 21:55:42     self._target(*self._args, **self._kwargs)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-09-29 21:55:42     target(sockets=sockets)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
2023-09-29 21:55:42     return asyncio.run(self.serve(sockets=sockets))
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2023-09-29 21:55:42     return runner.run(main)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2023-09-29 21:55:42     return self._loop.run_until_complete(task)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
2023-09-29 21:55:42     self.run_forever()
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
2023-09-29 21:55:42     self._run_once()
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
2023-09-29 21:55:42     handle._run()
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
2023-09-29 21:55:42     self._context.run(self._callback, *self._args)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-09-29 21:55:42     result = await app(  # type: ignore[func-returns-value]
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-09-29 21:55:42     return await self.app(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2023-09-29 21:55:42     await super().__call__(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-09-29 21:55:42     await self.middleware_stack(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-09-29 21:55:42     await self.app(scope, receive, _send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2023-09-29 21:55:42     await self.simple_response(scope, receive, send, request_headers=headers)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2023-09-29 21:55:42     await self.app(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-09-29 21:55:42     await self.app(scope, receive, sender)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-09-29 21:55:42     await self.app(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-09-29 21:55:42     await route.handle(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-09-29 21:55:42     await self.app(scope, receive, send)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-09-29 21:55:42     response = await func(request)
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2023-09-29 21:55:42     raw_response = await run_endpoint_function(
2023-09-29 21:55:42   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-09-29 21:55:42     return await dependant.call(**values)
2023-09-29 21:55:42   File "/code/routes/knowledge_routes.py", line 36, in list_knowledge_in_brain_endpoint

**Comment by lugfug** [comment]
I'm in the same boat as @georgeqin96 I updated to 0.0.85 (from 0.0.81) and all my data is gone. Likewise, the interface is unstable and keeps trying to automatically reload. NONE of my settings remain after the update. 

It seems these updates are so fragile.
