### ISSUE TITLE
Unable to upload file to default brain

### ISSUE THREAD

**Issue by massappa** [StanGirard/quivr#1350]
### What happened?

Failed to upload file. Network error

### Relevant log output

```bash
This is my backend/.env =
SUPABASE_SERVICE_KEY=
OPENAI_API_KEY=
JWT_SECRET_KEY=
AUTHENTICATE=true
GOOGLE_APPLICATION_CREDENTIALS="/.config/gcloud/application_default_credentials.json"
GOOGLE_CLOUD_PROJECT=""
MAX_BRAIN_SIZE=52428800
MAX_REQUESTS_NUMBER=200
ANTHROPIC_API_KEY="xxxxxxxxxxxx"
MAX_BRAIN_PER_USER=5
CELERY_BROKER_URL="redis://redis:6379/0"
CELEBRY_BROKER_QUEUE_NAME="quivr-preview.fifo"
PRIVATE=False
MODEL_PATH=./local_models/ggml-gpt4all-j-v1.3-groovy.bin
RESEND_API_KEY=<change-me>
RESEND_EMAIL_ADDRESS=onboarding@resend.dev
CRAWL_DEPTH=1. I start backend with "uvicorn main:app --reload --host 0.0.0.0 --port 5050 --workers 6". I start the frontend with "npm run dev". i have the latest tables.sql in my supabase. I am getting this error when I upload a file in default brain ```routes.upload_routes: Knowledge id=UUID('604099d8-ebed-45da-8cd1-54731722cda0') brain_id=UUID('1e1527a6-4aff-4e4b-9b1d-3215c1b68033') file_name='shape.pdf' url=None extension='.pdf' added successfully
2023-10-06 20:02:43,889:ERROR - Connection to Redis lost: Retry (0/20) now.
2023-10-06 20:02:43,892:ERROR - Connection to Redis lost: Retry (1/20) in 1.00 second.
2023-10-06 20:02:44,910:ERROR - Connection to Redis lost: Retry (2/20) in 1.00 second.
2023-10-06 20:02:45,920:ERROR - Connection to Redis lost: Retry (3/20) in 1.00 second.
2023-10-06 20:02:46,926:ERROR - Connection to Redis lost: Retry (4/20) in 1.00 second.
2023-10-06 20:02:47,933:ERROR - Connection to Redis lost: Retry (5/20) in 1.00 second.
2023-10-06 20:02:48,943:ERROR - Connection to Redis lost: Retry (6/20) in 1.00 second.
2023-10-06 20:02:49,950:ERROR - Connection to Redis lost: Retry (7/20) in 1.00 second.
2023-10-06 20:02:50,959:ERROR - Connection to Redis lost: Retry (8/20) in 1.00 second.
2023-10-06 20:02:51,968:ERROR - Connection to Redis lost: Retry (9/20) in 1.00 second.
2023-10-06 20:02:52,977:ERROR - Connection to Redis lost: Retry (10/20) in 1.00 second.
2023-10-06 20:02:53,983:ERROR - Connection to Redis lost: Retry (11/20) in 1.00 second.
2023-10-06 20:02:54,988:ERROR - Connection to Redis lost: Retry (12/20) in 1.00 second.
2023-10-06 20:02:55,999:ERROR - Connection to Redis lost: Retry (13/20) in 1.00 second.
2023-10-06 20:02:57,008:ERROR - Connection to Redis lost: Retry (14/20) in 1.00 second.
2023-10-06 20:02:58,012:ERROR - Connection to Redis lost: Retry (15/20) in 1.00 second.
2023-10-06 20:02:59,023:ERROR - Connection to Redis lost: Retry (16/20) in 1.00 second.
2023-10-06 20:03:00,030:ERROR - Connection to Redis lost: Retry (17/20) in 1.00 second.
2023-10-06 20:03:01,033:ERROR - Connection to Redis lost: Retry (18/20) in 1.00 second.
2023-10-06 20:03:02,039:ERROR - Connection to Redis lost: Retry (19/20) in 1.00 second.
2023-10-06 20:03:03,047:CRITICAL - 
Retry limit exceeded while trying to reconnect to the Celery redis result store backend. The Celery application must be restarted.

INFO:     127.0.0.1:62725 - "POST /upload?brain_id=1e1527a6-4aff-4e4b-9b1d-3215c1b68033&chat_id=4dd67c36-9783-4993-b317-48189428e865 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 955, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 119, in reconnect_on_error
    yield
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 169, in _consume_from
    self._pubsub.subscribe(key)
  File "quivr/.venv/lib/python3.11/site-packages/redis/client.py", line 1623, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/client.py", line 1458, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 955, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quivr/.venv/lib/python3.11/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "quivr/.venv/lib/python3.11/site-packages/celery/app/base.py", line 787, in send_task
    self.backend.on_task_call(P, task_id)
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 365, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 161, in consume_from
    return self.start(task_id)
           ^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 139, in start
    self._consume_from(initial_task_id)
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 168, in _consume_from
    with self.reconnect_on_error():
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 122, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 376, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/celery/backends/redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 1976, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "quivr/.venv/lib/python3.11/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "quivr/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "quivr/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "quivr/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "quivr/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "quivr/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/backend/routes/upload_routes.py", line 111, in upload_file
    process_file_and_notify.delay(
  File "quivr/.venv/lib/python3.11/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "quivr/.venv/lib/python3.11/site-packages/celery/app/base.py", line 785, in send_task
    with P.connection._reraise_as_library_errors():
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "quivr/.venv/lib/python3.11/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.```
```

**Comment by israellev** [comment]
@massappa Did you solve it?
I have the same issue of `Connection to Redis lost` and after that the same error in the `/upload` API.

**Comment by jonazk** [comment]
@israellev have the same challenge running it on AWS ECS fargate (backend only). How did you solve it?
