### ISSUE TITLE
[Bug]: stopped loading at 38/42

### ISSUE THREAD

**Issue by gwwharton** [StanGirard/quivr#1354]
### What happened?

A bug happened! I'm not sure what happened as I followed the instructions in the video.

### Relevant log output

```bash
[+] Building 0.9s (38/42)                                  docker:desktop-linux
 => [worker internal] load .dockerignore                                   0.0s
 => => transferring context: 2B                                            0.0s
 => [worker internal] load build definition from Dockerfile                0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [backend-core internal] load metadata for docker.io/library/python:3.  0.6s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 60B                                           0.0s
 => [frontend internal] load build definition from Dockerfile.dev          0.0s
 => => transferring dockerfile: 780B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:18.13.0-  0.4s
 => [worker internal] load build context                                   0.0s
 => => transferring context: 9.54kB                                        0.0s
 => [backend-core 1/7] FROM docker.io/library/python:3.11-slim-bullseye@s  0.0s
 => [frontend internal] load build context                                 0.0s
 => => transferring context: 56.33kB                                       0.0s
 => [frontend 1/9] FROM docker.io/library/node:18.13.0-alpine@sha256:fda9  0.0s
 => CACHED [flower 2/7] RUN apt-get update && apt-get install -y     libg  0.0s
 => CACHED [flower 3/7] WORKDIR /code                                      0.0s
 => CACHED [worker 4/7] COPY ./requirements.txt .                          0.0s
 => CACHED [worker 5/7] RUN pip install --upgrade pip                      0.0s
 => CACHED [worker 6/7] RUN pip install --no-cache-dir -r requirements.tx  0.0s
 => CACHED [worker 7/7] COPY . .                                           0.0s
 => [worker] exporting to image                                            0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:90fb5e0f9c018eebbc6b997e72d3ec6cbd056734dec95  0.0s
 => => naming to docker.io/library/quivr-worker                            0.0s
 => CACHED [frontend 2/9] RUN apk add --update --no-cache python3 make g+  0.0s
 => CACHED [frontend 3/9] RUN python3 -m ensurepip                         0.0s
 => CACHED [frontend 4/9] RUN pip3 install --no-cache --upgrade pip setup  0.0s
 => CACHED [frontend 5/9] RUN mkdir -p /app                                0.0s
 => CACHED [frontend 6/9] WORKDIR /app                                     0.0s
 => CACHED [frontend 7/9] COPY package*.json yarn.lock ./                  0.0s
 => CACHED [frontend 8/9] RUN yarn install --network-timeout 1000000       0.0s
 => CACHED [frontend 9/9] COPY . .                                         0.0s
 => [frontend] exporting to image                                          0.1s
 => => exporting layers                                                    0.1s
 => => writing image sha256:5130dc07a659e5afa11cca12e1d25e86bcae8babc0482  0.0s
 => => naming to docker.io/library/quivr-frontend                          0.0s
 => [backend-core internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [backend-core internal] load .dockerignore                             0.0s
 => => transferring context: 2B                                            0.0s
 => [flower internal] load build definition from Dockerfile                0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [flower internal] load .dockerignore                                   0.0s
 => => transferring context: 2B                                            0.0s
 => [backend-core internal] load build context                             0.0s
 => => transferring context: 9.54kB                                        0.0s
 => [flower internal] load build context                                   0.0s
 => => transferring context: 9.54kB                                        0.0s
 => CACHED [flower 4/7] COPY ./requirements.txt .                          0.0s
 => CACHED [flower 5/7] RUN pip install --upgrade pip                      0.0s
 => CACHED [flower 6/7] RUN pip install --no-cache-dir -r requirements.tx  0.0s
 => CACHED [flower 7/7] COPY . .                                           0.0s
 => [flower] exporting to image                                            0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:cc6003930526e2f0e4731a42ba0d6b89059d1f5f54f50  0.0s
 => => naming to docker.io/library/quivr-flower                            0.0s
 => [backend-core] exporting to image                                      0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:59184764e51646bba63ecadc7b88cd960320a1aa2a3a9  0.0s
 => => naming to docker.io/library/quivr-backend-core                      0.0s
[+] Running 6/6
 ✔ Network quivr_default   Created                                         0.0s 
 ✔ Container web           Created                                         8.5s 
 ✔ Container redis         Created                                         0.0s 
 ✔ Container worker        Created                                         0.0s 
 ✔ Container flower        Created                                         0.0s 
 ✔ Container backend-core  Created                                         0.0s 
Attaching to backend-core, flower, redis, web, worker
redis         | 1:C 08 Oct 2023 15:50:01.528 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis         | 1:C 08 Oct 2023 15:50:01.528 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis         | 1:C 08 Oct 2023 15:50:01.528 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis         | 1:M 08 Oct 2023 15:50:01.529 * monotonic clock: POSIX clock_gettime
redis         | 1:M 08 Oct 2023 15:50:01.529 * Running mode=standalone, port=6379.
redis         | 1:M 08 Oct 2023 15:50:01.529 * Server initialized
redis         | 1:M 08 Oct 2023 15:50:01.529 * Ready to accept connections tcp
web           | yarn run v1.22.19
web           | $ next dev
backend-core  | INFO:     Will watch for changes in these directories: ['/code']
backend-core  | WARNING:  "workers" flag is ignored when reloading is enabled.
backend-core  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend-core  | INFO:     Started reloader process [1] using StatReload
web           | - info Loaded env from /app/.env
web           | - ready started server on [::]:3000, url: http://localhost:3000
web           | Attention: Next.js now collects completely anonymous telemetry regarding usage.
web           | This information is used to shape Next.js' roadmap and prioritize features.
web           | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
web           | https://nextjs.org/telemetry
web           | 
backend-core  | Process SpawnProcess-1:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend-core  |     self.run()
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend-core  |     self._target(*self._args, **self._kwargs)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend-core  |     target(sockets=sockets)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend-core  |     return asyncio.run(self.serve(sockets=sockets))
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend-core  |     return runner.run(main)
backend-core  |            ^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend-core  |     return self._loop.run_until_complete(task)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend-core  |     return future.result()
backend-core  |            ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend-core  |     config.load()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend-core  |     self.loaded_app = import_from_string(self.app)
backend-core  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend-core  |     module = importlib.import_module(module_str)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-core  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-core  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-core  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-core  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-core  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-core  |   File "/code/main.py", line 16, in <module>
backend-core  |     from routes.api_key_routes import api_key_router
backend-core  |   File "/code/routes/api_key_routes.py", line 6, in <module>
backend-core  |     from auth import AuthBearer, get_current_user
backend-core  |   File "/code/auth/__init__.py", line 1, in <module>
backend-core  |     from .auth_bearer import AuthBearer, get_current_user
backend-core  |   File "/code/auth/auth_bearer.py", line 5, in <module>
backend-core  |     from auth.jwt_token_handler import decode_access_token, verify_token
backend-core  |   File "/code/auth/jwt_token_handler.py", line 13, in <module>
backend-core  |     raise ValueError("JWT_SECRET_KEY environment variable not set")
backend-core  | ValueError: JWT_SECRET_KEY environment variable not set
worker        | /usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
worker        | absolutely not recommended!
worker        | 
worker        | Please specify a different user using the --uid option.
worker        | 
worker        | User information: uid=0 euid=0 gid=0 egid=0
worker        | 
worker        |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker        |  
worker        |  -------------- celery@de2c4ddc43ba v5.2.7 (dawn-chorus)
worker        | --- ***** ----- 
worker        | -- ******* ---- Linux-6.4.16-linuxkit-aarch64-with-glibc2.31 2023-10-08 15:50:03
worker        | - *** --- * --- 
worker        | - ** ---------- [config]
worker        | - ** ---------- .> app:         celery_worker:0xffffacde4c50
worker        | - ** ---------- .> transport:   redis://redis:6379/0
worker        | - ** ---------- .> results:     redis://redis:6379/0
worker        | - *** --- * --- .> concurrency: 9 (prefork)
worker        | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker        | --- ***** ----- 
worker        |  -------------- [queues]
worker        |                 .> celery           exchange=celery(direct) key=celery
worker        |                 
worker        | 
worker        | [tasks]
worker        |   . celery_task.create_embedding_for_document
worker        |   . process_crawl_and_notify
worker        |   . process_file_and_notify
worker        | 
flower        | 2023-10-08 15:50:03,070:INFO - Visit me at http://0.0.0.0:5555
flower        | 2023-10-08 15:50:03,073:INFO - Broker: redis://redis:6379/0
flower        | 2023-10-08 15:50:03,074:INFO - Registered tasks: 
flower        | ['celery.accumulate',
flower        |  'celery.backend_cleanup',
flower        |  'celery.chain',
flower        |  'celery.chord',
flower        |  'celery.chord_unlock',
flower        |  'celery.chunks',
flower        |  'celery.group',
flower        |  'celery.map',
flower        |  'celery.starmap',
flower        |  'celery_task.create_embedding_for_document',
flower        |  'process_crawl_and_notify',
flower        |  'process_file_and_notify']
flower        | 2023-10-08 15:50:03,079:INFO - Connected to redis://redis:6379/0
worker        | [2023-10-08 15:50:03,641: INFO/MainProcess] Connected to redis://redis:6379/0
worker        | [2023-10-08 15:50:03,643: INFO/MainProcess] mingle: searching for neighbors
flower        | 2023-10-08 15:50:04,104:WARNING - Inspect method active failed
flower        | 2023-10-08 15:50:04,105:WARNING - Inspect method active_queues failed
flower        | 2023-10-08 15:50:04,106:WARNING - Inspect method reserved failed
flower        | 2023-10-08 15:50:04,107:WARNING - Inspect method registered failed
flower        | 2023-10-08 15:50:04,108:WARNING - Inspect method stats failed
flower        | 2023-10-08 15:50:04,108:WARNING - Inspect method conf failed
flower        | 2023-10-08 15:50:04,109:WARNING - Inspect method scheduled failed
flower        | 2023-10-08 15:50:04,109:WARNING - Inspect method revoked failed
web           | - event compiled client and server successfully in 135 ms (20 modules)
web           | - wait compiling...
worker        | [2023-10-08 15:50:04,648: INFO/MainProcess] mingle: all alone
worker        | [2023-10-08 15:50:04,653: INFO/MainProcess] celery@de2c4ddc43ba ready.
web           | - event compiled client and server successfully in 107 ms (20 modules)
web           | - info Loaded env from /app/.env
web           | - info Loaded env from /app/.env
worker        | [2023-10-08 15:50:08,085: INFO/MainProcess] Events of group {task} enabled by remote.
```

**Comment by gwwharton** [comment]
Now it stops at 40/44

[+] Building 1.1s (40/44)                                  docker:desktop-linux
 => [worker internal] load build definition from Dockerfile                0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [worker internal] load .dockerignore                                   0.0s
 => => transferring context: 2B                                            0.0s
 => [backend-core internal] load metadata for docker.io/library/python:3.  0.9s
 => [frontend internal] load build definition from Dockerfile.dev          0.0s
 => => transferring dockerfile: 780B                                       0.0s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 60B                                           0.0s
 => [frontend internal] load metadata for docker.io/library/node:18.13.0-  0.6s
 => [worker auth] library/python:pull token for registry-1.docker.io       0.0s
 => [frontend auth] library/node:pull token for registry-1.docker.io       0.0s
 => [frontend internal] load build context                                 0.1s
 => => transferring context: 56.36kB                                       0.0s
 => [frontend 1/9] FROM docker.io/library/node:18.13.0-alpine@sha256:fda9  0.0s
 => CANCELED [backend-core 1/7] FROM docker.io/library/python:3.11-slim-b  0.0s
 => [worker internal] load build context                                   0.0s
 => => transferring context: 16.24kB                                       0.0s
 => CACHED [flower 2/7] RUN apt-get update && apt-get install -y     libg  0.0s
 => CACHED [flower 3/7] WORKDIR /code                                      0.0s
 => CACHED [worker 4/7] COPY ./requirements.txt .                          0.0s
 => CACHED [worker 5/7] RUN pip install --upgrade pip                      0.0s
 => CACHED [worker 6/7] RUN pip install --no-cache-dir -r requirements.tx  0.0s
 => CACHED [worker 7/7] COPY . .                                           0.0s
 => [worker] exporting to image                                            0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:35a4bd0cf2453e89a0a36afc3a4cc04f7856fb714d4ee  0.0s
 => => naming to docker.io/library/quivr-worker                            0.0s
 => CACHED [frontend 2/9] RUN apk add --update --no-cache python3 make g+  0.0s
 => CACHED [frontend 3/9] RUN python3 -m ensurepip                         0.0s
 => CACHED [frontend 4/9] RUN pip3 install --no-cache --upgrade pip setup  0.0s
 => CACHED [frontend 5/9] RUN mkdir -p /app                                0.0s
 => CACHED [frontend 6/9] WORKDIR /app                                     0.0s
 => CACHED [frontend 7/9] COPY package*.json yarn.lock ./                  0.0s
 => CACHED [frontend 8/9] RUN yarn install --network-timeout 1000000       0.0s
 => CACHED [frontend 9/9] COPY . .                                         0.0s
 => [frontend] exporting to image                                          0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:5812b5fd0a066d9d6efcd2920bd74e98540c2ec22abac  0.0s
 => => naming to docker.io/library/quivr-frontend                          0.0s
 => [backend-core internal] load .dockerignore                             0.0s
 => => transferring context: 2B                                            0.0s
 => [backend-core internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [flower internal] load .dockerignore                                   0.0s
 => => transferring context: 2B                                            0.0s
 => [flower internal] load build definition from Dockerfile                0.0s
 => => transferring dockerfile: 948B                                       0.0s
 => [flower internal] load build context                                   0.0s
 => => transferring context: 16.24kB                                       0.0s
 => [backend-core internal] load build context                             0.0s
 => => transferring context: 16.24kB                                       0.0s
 => CACHED [flower 4/7] COPY ./requirements.txt .                          0.0s
 => CACHED [flower 5/7] RUN pip install --upgrade pip                      0.0s
 => CACHED [flower 6/7] RUN pip install --no-cache-dir -r requirements.tx  0.0s
 => CACHED [flower 7/7] COPY . .                                           0.0s
 => [backend-core] exporting to image                                      0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:c790094d60724cdeab830b034a42aa9031c610a36e5fb  0.0s
 => => naming to docker.io/library/quivr-backend-core                      0.0s
 => [flower] exporting to image                                            0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:c2f797ad2d904b7c7f3ead02b180c54fee299c86de09c  0.0s
 => => naming to docker.io/library/quivr-flower                            0.0s
[+] Running 5/0
 ✔ Container redis         Running                                         0.0s 
 ✔ Container web           Running                                         0.0s 
 ✔ Container worker        Running                                         0.0s 
 ✔ Container backend-core  Running                                         0.0s 
 ✔ Container flower        Running                                         0.0s 
Attaching to backend-core, flower, redis, web, worker
