### ISSUE TITLE
[Bug]: installation does not succeed

### ISSUE THREAD

**Issue by stefangweichinger** [StanGirard/quivr#1376]
### What happened?

Following the installation HOWTO as good as I understand them.

I edited these variables:

```
NEXT_PUBLIC_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY

SUPABASE_URL
SUPABASE_SERVICE_KEY

OPENAI_API_KEY

JWT_SECRET_KEY
```

Testing on 2 different docker servers (fedora, debian).

Created a 2nd supabase project and reconfigured variables. No success.

* webGUI looks incorrect
* can't signup or login
* no entries get created in the tables

I am currently at commit 28a6dc169af633c38459765a9f8b6bf32053a5d0

### Relevant log output

```bash
docker-compose up
Creating network "quivr_default" with the default driver
Creating redis ... done
Creating web   ... done
Creating worker ... done
Creating flower       ... done
Creating backend-core ... done
Attaching to web, redis, worker, flower, backend-core
redis           | 1:C 10 Oct 2023 09:50:08.790 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis           | 1:C 10 Oct 2023 09:50:08.790 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis           | 1:C 10 Oct 2023 09:50:08.790 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis           | 1:C 10 Oct 2023 09:50:08.790 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis           | 1:M 10 Oct 2023 09:50:08.791 * monotonic clock: POSIX clock_gettime
redis           | 1:M 10 Oct 2023 09:50:08.791 * Running mode=standalone, port=6379.
web             | yarn run v1.22.19
redis           | 1:M 10 Oct 2023 09:50:08.791 * Server initialized
redis           | 1:M 10 Oct 2023 09:50:08.791 * Ready to accept connections tcp
web             | $ next start
web             | - ready started server on [::]:3000, url: http://localhost:3000
web             | - info Loaded env from /app/.env
web             | - info Loaded env from /app/.env
backend-core    | INFO:     Will watch for changes in these directories: ['/code']
backend-core    | WARNING:  "workers" flag is ignored when reloading is enabled.
backend-core    | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend-core    | INFO:     Started reloader process [1] using StatReload
worker          | /usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
worker          | absolutely not recommended!
worker          | 
worker          | Please specify a different user using the --uid option.
worker          | 
worker          | User information: uid=0 euid=0 gid=0 egid=0
worker          | 
worker          |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker          |  
worker          |  -------------- celery@759d22d127d4 v5.2.7 (dawn-chorus)
worker          | --- ***** ----- 
worker          | -- ******* ---- Linux-6.5.6-300.fc39.x86_64-x86_64-with-glibc2.31 2023-10-10 09:50:10
worker          | - *** --- * --- 
worker          | - ** ---------- [config]
worker          | - ** ---------- .> app:         celery_worker:0x7f9545984150
worker          | - ** ---------- .> transport:   redis://redis:6379/0
worker          | - ** ---------- .> results:     redis://redis:6379/0
worker          | - *** --- * --- .> concurrency: 16 (prefork)
worker          | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker          | --- ***** ----- 
worker          |  -------------- [queues]
worker          |                 .> celery           exchange=celery(direct) key=celery
worker          |                 
worker          | 
worker          | [tasks]
worker          |   . celery_task.create_embedding_for_document
worker          |   . process_crawl_and_notify
worker          |   . process_file_and_notify
worker          | 
flower          | 2023-10-10 09:50:11,361:INFO - Visit me at http://0.0.0.0:5555
flower          | 2023-10-10 09:50:11,365:INFO - Broker: redis://redis:6379/0
flower          | 2023-10-10 09:50:11,367:INFO - Registered tasks: 
flower          | ['celery.accumulate',
flower          |  'celery.backend_cleanup',
flower          |  'celery.chain',
flower          |  'celery.chord',
flower          |  'celery.chord_unlock',
flower          |  'celery.chunks',
flower          |  'celery.group',
flower          |  'celery.map',
flower          |  'celery.starmap',
flower          |  'celery_task.create_embedding_for_document',
flower          |  'process_crawl_and_notify',
flower          |  'process_file_and_notify']
flower          | 2023-10-10 09:50:11,372:INFO - Connected to redis://redis:6379/0
backend-core    | 2023-10-10 09:50:11,768:INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
backend-core    | 2023-10-10 09:50:11,768:INFO - NumExpr defaulting to 8 threads.
worker          | [2023-10-10 09:50:12,006: INFO/MainProcess] Connected to redis://redis:6379/0
worker          | [2023-10-10 09:50:12,008: INFO/MainProcess] mingle: searching for neighbors
backend-core    | INFO:     Started server process [8]
backend-core    | INFO:     Waiting for application startup.
flower          | 2023-10-10 09:50:12,406:WARNING - Inspect method scheduled failed
flower          | 2023-10-10 09:50:12,407:WARNING - Inspect method active failed
flower          | 2023-10-10 09:50:12,415:WARNING - Inspect method conf failed
flower          | 2023-10-10 09:50:12,415:WARNING - Inspect method revoked failed
flower          | 2023-10-10 09:50:12,417:WARNING - Inspect method reserved failed
flower          | 2023-10-10 09:50:12,417:WARNING - Inspect method stats failed
flower          | 2023-10-10 09:50:12,417:WARNING - Inspect method registered failed
flower          | 2023-10-10 09:50:12,418:WARNING - Inspect method active_queues failed
worker          | [2023-10-10 09:50:13,017: INFO/MainProcess] mingle: all alone
worker          | [2023-10-10 09:50:13,045: INFO/MainProcess] celery@759d22d127d4 ready.
backend-core    | [INFO] Using already downloaded file pandoc-3.1.8-1-amd64.deb
backend-core    | 2023-10-10 09:50:13,154:INFO - Using already downloaded file pandoc-3.1.8-1-amd64.deb
backend-core    | [INFO] Unpacking pandoc-3.1.8-1-amd64.deb to tempfolder...
backend-core    | 2023-10-10 09:50:13,155:INFO - Unpacking pandoc-3.1.8-1-amd64.deb to tempfolder...
backend-core    | [INFO] Copying pandoc to /root/bin ...
backend-core    | 2023-10-10 09:50:13,801:INFO - Copying pandoc to /root/bin ...
backend-core    | [INFO] Making /root/bin/pandoc executeable...
backend-core    | 2023-10-10 09:50:13,865:INFO - Making /root/bin/pandoc executeable...
backend-core    | [INFO] Copying copyright to /root/bin ...
backend-core    | 2023-10-10 09:50:13,865:INFO - Copying copyright to /root/bin ...
backend-core    | INFO:     Application startup complete.
worker          | [2023-10-10 09:50:16,374: INFO/MainProcess] Events of group {task} enabled by remote.
web             | react-i18next:: You will need to pass in an i18next instance by using initReactI18next
web             | i18next: languageChanged en
web             | i18next: initialized {
web             |   debug: true,
web             |   initImmediate: true,
web             |   ns: [ 'translation' ],
web             |   defaultNS: 'translation',
web             |   fallbackLng: [ 'en' ],
web             |   fallbackNS: false,
web             |   supportedLngs: false,
web             |   nonExplicitSupportedLngs: false,
web             |   load: 'all',
web             |   preload: false,
web             |   simplifyPluralSuffix: true,
web             |   keySeparator: '.',
web             |   nsSeparator: ':',
web             |   pluralSeparator: '_',
web             |   contextSeparator: '_',
web             |   partialBundledLanguages: false,
web             |   saveMissing: false,
web             |   updateMissing: false,
web             |   saveMissingTo: 'fallback',
web             |   saveMissingPlurals: true,
web             |   missingKeyHandler: false,
web             |   missingInterpolationHandler: false,
web             |   postProcess: false,
web             |   postProcessPassResolved: false,
web             |   returnNull: false,
web             |   returnEmptyString: true,
web             |   returnObjects: false,
web             |   joinArrays: false,
web             |   returnedObjectHandler: false,
web             |   parseMissingKeyHandler: false,
web             |   appendNamespaceToMissingKey: false,
web             |   appendNamespaceToCIMode: false,
web             |   overloadTranslationOptionHandler: [Function: handle],
web             |   interpolation: {
web             |     escapeValue: false,
web             |     format: [Function: bound format],
web             |     prefix: '{{',
web             |     suffix: '}}',
web             |     formatSeparator: ',',
web             |     unescapePrefix: '-',
web             |     nestingPrefix: '$t(',
web             |     nestingSuffix: ')',
web             |     nestingOptionsSeparator: ',',
web             |     maxReplaces: 1000,
web             |     skipOnVariables: true
web             |   },
web             |   lng: 'en',
web             |   resources: {
web             |     en: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     },
web             |     es: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     },
web             |     fr: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     },
web             |     ptbr: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     },
web             |     ru: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     },
web             |     zh_cn: {
web             |       brain: [Object],
web             |       chat: [Object],
web             |       config: [Object],
web             |       explore: [Object],
web             |       invitation: [Object],
web             |       login: [Object],
web             |       logout: [Object],
web             |       signUp: [Object],
web             |       translation: [Object],
web             |       updatePassword: [Object],
web             |       upload: [Object],
web             |       user: [Object],
web             |       delete_or_unsubscribe_from_brain: [Object],
web             |       knowledge: {}
web             |     }
web             |   },
web             |   ignoreJSONStructure: true
web             | }
^CGracefully stopping... (press Ctrl+C again to force)
Stopping backend-core ... done
Stopping flower       ... done
Stopping worker       ... done
Stopping web          ... done
Stopping redis        ... done
```

**Comment by stefangweichinger** [comment]
@dosu-bot

This automated reply seems not to match my issue fully.
As I want to use OPENAI it'S not a "fully local" installation IMO.

So I assume I don't need CUDA etc ...

I'd appreciate a guide how to check if the application stack is able to talk to the supabase-API correctly.

For now I will try to use quotes around the keys ...

**Comment by stefangweichinger** [comment]
accessing http://0.0.0.0:3000/chat brings:

```
backend-core    | INFO:     172.20.0.1:42178 - "GET / HTTP/1.1" 200 OK
backend-core    | INFO:     172.20.0.1:42192 - "GET /robots.txt HTTP/1.1" 404 Not Found
backend-core    | INFO:     172.20.0.1:42178 - "GET /favicon.ico HTTP/1.1" 404 Not Found
web             | ReferenceError: sessionStorage is not defined
web             |     at redirectToLogin (/app/.next/server/chunks/693.js:85:5)
web             |     at Layout (/app/.next/server/chunks/565.js:2685:51)
web             |     at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:273)
web             |     at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:11)
web             |     at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
web             |     at kg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
web             |     at mg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)
web             |     at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:350)
web             |     at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:191)
web             |     at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
```
