### ISSUE TITLE
[Bug]: Can not load the brains after upgrade to version 89

### ISSUE THREAD

**Issue by BabaSarf** [StanGirard/quivr#1392]
### What happened?

after the upgrade to version 89 Login to Quivr but the brains are not loaded and the brain library is empty. and I get the following error in the docker terminal

### Relevant log output

```bash
1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/brain_routes.py", line 50, in brain_endpoint
backend-core  |     brains = get_user_brains(current_user.id)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_user_brains.py", line 9, in get_user_brains
backend-core  |     results = supabase_db.get_user_brains(user_id)  # type: ignore
backend-core  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 68, in get_user_brains
backend-core  |     MinimalBrainEntity(
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for MinimalBrainEntity
backend-core  | status
backend-core  |   none is not an allowed value (type=type_error.none.not_allowed)
redis         | 1:M 11 Oct 2023 23:53:14.011 * 1 changes in 3600 seconds. Saving...
redis         | 1:M 11 Oct 2023 23:53:14.011 * Background saving started by pid 31
redis         | 31:C 11 Oct 2023 23:53:14.026 * DB saved on disk
redis         | 31:C 11 Oct 2023 23:53:14.026 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis         | 1:M 11 Oct 2023 23:53:14.111 * Background saving terminated with success
backend-core  | INFO:     192.168.1.111:59388 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.111:59388 - "OPTIONS /brains/default/ HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.111:59406 - "OPTIONS /prompts HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.1.111:59392 - "GET /brains/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/brain_routes.py", line 50, in brain_endpoint
backend-core  |     brains = get_user_brains(current_user.id)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_user_brains.py", line 9, in get_user_brains
backend-core  |     results = supabase_db.get_user_brains(user_id)  # type: ignore
backend-core  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 68, in get_user_brains
backend-core  |     MinimalBrainEntity(
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for MinimalBrainEntity
backend-core  | status
backend-core  |   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by BabaSarf** [comment]
Thanks for your reply. it guided me to the brain table in Supabase. I had some null values in the brain table Replace NULL value with correct data and it works now . ChatGPT suggests that we modify the code to handle cases where these fields might be NULL in the database
class Brain(Repository):
    # ...

    def get_user_brains(self, user_id) -> list[MinimalBrainEntity]:
        response = (
            self.db.from_("brains_users")
            .select("id:brain_id, rights, brains (brain_id, name, status, description, model)")
            .filter("user_id", "eq", user_id)
            .execute()
        )

        user_brains: list[MinimalBrainEntity] = []

        for item in response.data:
            # Handle NULL values by providing default values
            name = item["brains"]["name"]
            rights = item["rights"]
            status = item["brains"].get("status", "unknown")
            description = item["brains"].get("description", "No description")
            model = item["brains"].get("model", "No model")

            user_brains.append(
                MinimalBrainEntity(
                    id=item["brains"]["brain_id"],
                    name=name,
                    rights=rights,
                    status=status,
                    description=description,
                    model=model
                )
            )

        return user_brains
Thanks again for guiding me in the right direction
