### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ted-b** [StanGirard/quivr#157]
env：WIN10+Docker Desktop
I don't know what happened. Does anyone know?

#0 2507.0 Collecting pyarrow>=4.0
#0 2507.2   Downloading pyarrow-12.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.9 MB)
#0 4345.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38.3/38.9 MB 165.4 MB/s eta 0:00:01
#0 4345.3 ERROR: Exception:
#0 4345.3 Traceback (most recent call last):
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
#0 4345.3     yield
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
#0 4345.3     data = self._fp_read(amt) if not fp_closed else b""
#0 4345.3            ^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
#0 4345.3     return self._fp.read(amt) if amt is not None else self._fp.read()
#0 4345.3            ^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/http/client.py", line 466, in read
#0 4345.3     s = self.fp.read(amt)
#0 4345.3         ^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
#0 4345.3     return self._sock.recv_into(b)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/ssl.py", line 1278, in recv_into
#0 4345.3     return self.read(nbytes, buffer)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/ssl.py", line 1134, in read
#0 4345.3     return self._sslobj.read(len, buffer)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3 TimeoutError: The read operation timed out
#0 4345.3
#0 4345.3 During handling of the above exception, another exception occurred:
#0 4345.3
#0 4345.3 Traceback (most recent call last):
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
#0 4345.3     status = run_func(*args)
#0 4345.3              ^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
#0 4345.3     return func(self, options, args)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 400, in run
#0 4345.3     requirement_set = resolver.resolve(
#0 4345.3                       ^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
#0 4345.3     result = self._result = resolver.resolve(
#0 4345.3                             ^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#0 4345.3     state = resolution.resolve(requirements, max_rounds=max_rounds)
#0 4345.3             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
#0 4345.3     failure_causes = self._attempt_to_pin_criterion(name)
#0 4345.3                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
#0 4345.3     criteria = self._get_updated_criteria(candidate)
#0 4345.3                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
#0 4345.3     self._add_to_criteria(criteria, requirement, parent=candidate)
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#0 4345.3     if not criterion.candidates:
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#0 4345.3     return bool(self._sequence)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#0 4345.3     return any(self)
#0 4345.3            ^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#0 4345.3     return (c for c in iterator if id(c) not in self._incompatible_ids)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#0 4345.3     candidate = func()
#0 4345.3                 ^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#0 4345.3     self._link_candidate_cache[link] = LinkCandidate(
#0 4345.3                                        ^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
#0 4345.3     super().__init__(
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
#0 4345.3     self.dist = self._prepare()
#0 4345.3                 ^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
#0 4345.3     dist = self._prepare_distribution()
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
#0 4345.3     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
#0 4345.3     return self._prepare_linked_requirement(req, parallel_builds)
#0 4345.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
#0 4345.3     local_file = unpack_url(
#0 4345.3                  ^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
#0 4345.3     file = get_http_url(
#0 4345.3            ^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
#0 4345.3     from_path, content_type = download(link, temp_dir.path)
#0 4345.3                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/network/download.py", line 147, in __call__
#0 4345.3     for chunk in chunks:
#0 4345.3   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
[+] Building 4357.6s (6/13)
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 771B                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                  1.3s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 2.21kB                                                                                0.0s
 => CACHED [1/9] FROM docker.io/library/node:18-alpine@sha256:1ccc70acda680aa4ba47f53e7c40b2d4d6892de74817128e066  0.0s
 => CANCELED [2/9] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python           4356.1s
failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade -r /code/requirements.txt --timeout 100" did not complete successfully: exit code: 2

**Comment by ted-b** [comment]
更换镜像源解决
