### ISSUE TITLE
[Bug]: Can't access to my default brain

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#1600]
### What happened?

A bug happened!
everything is fine, I can chet without brain. 
but I got prompt in log said I don't have authorization to my brain.
172.18.0.1:39842 - "GET /brains/8d652c38-481a-4d66-91d4-4624c29a4ccd/ HTTP/1.1" 401 Unauthorized

HOW to test?

**Comment by jerryshang** [comment]
@georgeqin96 you can check:
* is the browser session outdated? If i am right, the session timeout is about 1 hour.
* the JWT_TOKEN in backend/.env is correctedly set, If you run Quivr locally.

**Comment by georgeqin96** [comment]
> @georgeqin96 you can check:
> 
> * is the browser session outdated? If i am right, the session timeout is about 1 hour.
> * the JWT_TOKEN in backend/.env is correctedly set, If you run Quivr locally.

Thanks Jerryshang, 
No, it is not outdated. I used online supabase. I guessed it is maybe the network problem. but I couldn't figure out.

**Comment by georgeqin96** [comment]
> _🤖_
> 
> Based on the error message you've provided, it seems like you're encountering a "401 Unauthorized" error. This typically occurs when the server successfully processes the request but refuses to authorize it, often due to invalid or missing authentication credentials.
> 
> In the context of Quivr, the authentication is handled by passing an API key in the headers of the request. If you're receiving a "401 Unauthorized" error, it's likely that the API key you're using is either invalid or missing. Please ensure that you're correctly including a valid API key in the "Authorization" header of your requests. You can refer to the [backend/tests/test_brains.py](https://github.com/StanGirard/quivr/blob/main/backend/tests/test_brains.py) for an example of how to include the API key in the headers.
> 
> Additionally, there are a few similar issues that have been resolved in the past that might help you:
> 
> 1. [[Bug]: Unable to get brains on local](https://github.com/StanGirard/quivr/issues/1261) - In this issue, the user found an error in the `get_user_brains` method in the `backend/models/databases/supabase/brains.py` file. The method was searching in the brains table but using `id` not `brain_id`. The user suggested changing 'id' for 'brain_id' in the method. A PR was created for this fix: [PR #1272](https://github.com/StanGirard/quivr/pull/1272).
> 2. [[Issue] 401 Unauthorized](https://github.com/StanGirard/quivr/issues/648) - This issue might provide some additional context for your problem.
> 3. [bug!!! ](https://github.com/StanGirard/quivr/issues/410) - This issue also dealt with a similar problem.
> 
> Please try these solutions and let me know if your issue is resolved. If not, could you provide more details about your setup and the steps you're taking when you encounter this error? This will help me better understand your issue and provide a more accurate solution.
> 
> ## Sources
> * [[Bug]: Unable to get brains on local](https://github.com/StanGirard/quivr/issues/1261)
> * [[Issue] 401 Unauthorized](https://github.com/StanGirard/quivr/issues/648)
> * [bug!!! ](https://github.com/StanGirard/quivr/issues/410)
> * [backend/tests/test_brains.py](https://github.com/StanGirard/quivr/blob/main/backend/tests/test_brains.py)
> * [backend/auth/jwt_token_handler.py](https://github.com/StanGirard/quivr/blob/main/backend/auth/jwt_token_handler.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Thanks Bot. please tell me what this python enviroment to run the test_brains? can I run it in Jupyter Notebook?

**Comment by georgeqin96** [comment]
INFO:     172.18.0.1:44934 - "GET /brains/ HTTP/1.1" 500 Internal Server Error
2023-11-07 14:05:12 ERROR:    Exception in ASGI application
2023-11-07 14:05:12 Traceback (most recent call last):
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-11-07 14:05:12     result = await app(  # type: ignore[func-returns-value]
2023-11-07 14:05:12              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-11-07 14:05:12     return await self.app(scope, receive, send)
2023-11-07 14:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2023-11-07 14:05:12     await super().__call__(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-11-07 14:05:12     await self.middleware_stack(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-07 14:05:12     raise exc
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-07 14:05:12     await self.app(scope, receive, _send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2023-11-07 14:05:12     await self.simple_response(scope, receive, send, request_headers=headers)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2023-11-07 14:05:12     await self.app(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-07 14:05:12     raise exc
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-07 14:05:12     await self.app(scope, receive, sender)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-11-07 14:05:12     raise e
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-11-07 14:05:12     await self.app(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-11-07 14:05:12     await route.handle(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-11-07 14:05:12     await self.app(scope, receive, send)
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-11-07 14:05:12     response = await func(request)
2023-11-07 14:05:12                ^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2023-11-07 14:05:12     raw_response = await run_endpoint_function(
2023-11-07 14:05:12                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-11-07 14:05:12     return await dependant.call(**values)
2023-11-07 14:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/code/routes/brain_routes.py", line 39, in retrieve_all_brains_for_user
2023-11-07 14:05:12     brains = get_user_brains(current_user.id)
2023-11-07 14:05:12              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/code/repository/brain/get_user_brains.py", line 9, in get_user_brains
2023-11-07 14:05:12     results = supabase_db.get_user_brains(user_id)  # type: ignore
2023-11-07 14:05:12               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-07 14:05:12   File "/code/models/databases/supabase/brains.py", line 68, in get_user_brains
2023-11-07 14:05:12     MinimalBrainEntity(
2023-11-07 14:05:12   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-11-07 14:05:12 pydantic.error_wrappers.ValidationError: 1 validation error for MinimalBrainEntity
2023-11-07 14:05:12 status
2023-11-07 14:05:12   none is not an allowed value (type=type_error.none.not_allowed)

**Comment by georgeqin96** [comment]
above is log error in backend. but I can get brain_id in terminal:
>>> default_brain = get_user_default_brain('51c34138-20ba-4c5b-8a2a-29bec4e49896')
2023-11-07 05:41:00,848:INFO - HTTP Request: GET https://znzevohwgjjekemfdgqz.supabase.co/rest/v1/brains_users?select=brain_id&user_id=eq.51c34138-20ba-4c5b-8a2a-29bec4e49896&default_brain=eq.True "HTTP/1.1 200 OK"
2023-11-07 05:41:00,849 [INFO] repository.brain.get_default_user_brain: Default brain response: 8d652c38-481a-4d66-91d4-4624c29a4ccd
2023-11-07 05:41:00,849 [INFO] repository.brain.get_default_user_brain: Default brain id: 8d652c38-481a-4d66-91d4-4624c29a4ccd
2023-11-07 05:41:02,725:INFO - HTTP Request: GET https://znzevohwgjjekemfdgqz.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.8d652c38-481a-4d66-91d4-4624c29a4ccd "HTTP/1.1 200 OK"

**Comment by georgeqin96** [comment]
@dosu-bot
there is a Exception in ASGI application. please review above comment

**Comment by jerryshang** [comment]
> @dosu-bot there is a Exception in ASGI application. please review above comment

@georgeqin96 
Check if the brain record in supabase has a NULL field like name or something?

**Comment by georgeqin96** [comment]
> > @dosu-bot there is a Exception in ASGI application. please review above comment
> 
> @georgeqin96 Check if the brain record in supabase has a NULL field like name or something?

yes, serveral field is NULL

**Comment by georgeqin96** [comment]
> @georgeqin96 you can check:
> 
> * is the browser session outdated? If i am right, the session timeout is about 1 hour.
> * the JWT_TOKEN in backend/.env is correctedly set, If you run Quivr locally.

原来你在广州，非常感谢帮助解决了这个问题！
