### ISSUE TITLE
[Bug]: client-side exception has occurred

### ISSUE THREAD

**Issue by localdevjs** [StanGirard/quivr#1610]
### What happened?

Using latest commit: addcd27fce6ab41368d225798f8519a2c85a4f13

Create new project in supabase, update env variables in quivr, run ./migration script, then login using magic key. 

Trying to access brains-management page and I get a blank page with this error message:
Application error: a client-side exception has occurred (see the browser console for more information).

Viewing the browser console, multiple 401 and 404 errors, please see log output (I just hid the public domain name, the rest is unchanged).

### Relevant log output

```bash
934-686da9b879bf2b9d.js:1 i18next: languageChanged en
934-686da9b879bf2b9d.js:1 i18next: initialized Object
cdn.growthbook.io/api/features/%3Cignore-me-or-change-me%3E:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
6802-7a9cd4e1b24b345b.js:14 Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.
t_ @ 6802-7a9cd4e1b24b345b.js:14
1422-93dc72c51a266f36.js:1 Loaded June Analytics t
1422-93dc72c51a266f36.js:1 Loaded June Analytics t
script.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
%3Cignore-me-or-change-me%3E:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
api.june.so/sdk/identify:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
page-7d6fa5b5240e0ce7.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
596-da383d83991045a2.js:1 ChunkLoadError: Loading chunk 137 failed.
(error: https://$$MYDOMAIN$$/_next/static/chunks/app/brains-management/%5BbrainId%5D/page-7d6fa5b5240e0ce7.js)
    at l.f.j (webpack-47d904b3f6daa6ef.js:1:3765)
    at webpack-47d904b3f6daa6ef.js:1:1437
    at Array.reduce (<anonymous>)
    at l.e (webpack-47d904b3f6daa6ef.js:1:1403)
    at self.__next_chunk_load__ (596-da383d83991045a2.js:1:5797)
    at 596-da383d83991045a2.js:9:5751
    at 596-da383d83991045a2.js:9:5974
    at t (596-da383d83991045a2.js:9:6177)
window.console.error @ 596-da383d83991045a2.js:1
```

**Comment by localdevjs** [comment]
@dosu-bot Iniitally the page does load, I see the UI. Then after a second I see "default brain" appear for a fraction of a second and then the error appears in the webpage "client side exception".

The error in the log that appears right after the exception, is this:

```code
GET https://xxx/_next/static/chunks/app/brains-management/%5BbrainId%5D/page-7d6fa5b5240e0ce7.js net::ERR_ABORTED 404 (Not Found)

ChunkLoadError: Loading chunk 137 failed.
(error: https://xxxx/_next/static/chunks/app/brains-management/%5BbrainId%5D/page-7d6fa5b5240e0ce7.js)
    at l.f.j (webpack-47d904b3f6daa6ef.js:1:3765)
    at webpack-47d904b3f6daa6ef.js:1:1437
    at Array.reduce (<anonymous>)
    at l.e (webpack-47d904b3f6daa6ef.js:1:1403)
    at self.__next_chunk_load__ (596-da383d83991045a2.js:1:5797)
    at 596-da383d83991045a2.js:9:5751
    at 596-da383d83991045a2.js:9:5974
    at t (596-da383d83991045a2.js:9:6177)
```

**Comment by localdevjs** [comment]
Edited title, this same error appears when trying to chat as well. Page/UI loads, I type a question, page responds initially and then "client side exception" with the same "chunk loading error" failure in the web browser log.

No doubt I'm missing something here, I've double/triple check my env variables and they look good.
