### ISSUE TITLE
ar: /code/pandoc-3.1.2-1-amd64.deb is not a valid archive

### ISSUE THREAD

**Issue by shoufei403** [StanGirard/quivr#172]
Operating System:
ubuntu 20.04

Docker and Docker Compose versions:
Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.16.0

Problem I met:
when I run `docker compose up` to launch the app, the following error message come out.

```
backend  | 2023-05-26 14:25:41,661:INFO - NumExpr defaulting to 4 threads.
backend  | INFO:     Started server process [8]
backend  | INFO:     Waiting for application startup.
web      | - wait compiling /(home)/page (client and server)...
backend  | [INFO] Using already downloaded file pandoc-3.1.2-1-amd64.deb
backend  | 2023-05-26 14:25:46,859:INFO - Using already downloaded file pandoc-3.1.2-1-amd64.deb
backend  | [INFO] Unpacking pandoc-3.1.2-1-amd64.deb to tempfolder...
backend  | 2023-05-26 14:25:46,859:INFO - Unpacking pandoc-3.1.2-1-amd64.deb to tempfolder...
backend  | ar: /code/pandoc-3.1.2-1-amd64.deb is not a valid archive
backend  | ERROR:    Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend  |     async with self.lifespan_context(app) as maybe_state:
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend  |     await self._router.startup()
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend  |     await handler()
backend  |   File "/code/api.py", line 54, in startup_event
backend  |     pypandoc.download_pandoc()https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 267, in download_pandoc
backend  |     unpack(filename, targetfolder)
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 95, in _handle_linux
backend  |     subprocess.check_call(cmd)
backend  |   File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
backend  |     raise CalledProcessError(retcode, cmd)
backend  | subprocess.CalledProcessError: Command '['ar', 'x', '/code/pandoc-3.1.2-1-amd64.deb']' returned non-zero exit status 1.
backend  | 
backend  | ERROR:    Application startup failed. Exiting.
```

Is there something incompatible? 

If anyone figure this out, please comment below. I will very appreciate it.

**Comment by shoufei403** [comment]
By the way, I have finished `docker compose build` command.

**Comment by ReverseSystem001** [comment]
how do you solve it?
