### ISSUE TITLE
[Bug]: invalid credentials when calling get promps

### ISSUE THREAD

**Issue by bradennapier** [StanGirard/quivr#1781]
### What happened?

When setting up locally with all the default setup and following the guide, the following error is happening when attempting to call `/prompts` it would seem for some reason the response is invalid credentials.   I have tried fresh installs and get the same result.

### Relevant log output

```bash
backend-core                    | INFO:     192.168.65.1:24526 - "OPTIONS /prompts HTTP/1.1" 200 OK
supabase-kong                   | 172.19.0.8 - - [02/Dec/2023:10:41:19 +0000] "POST /rest/v1/prompts HTTP/1.1" 201 281 "-" "python-httpx/0.24.1"
backend-core                    | 2023-12-02 10:41:19,555:INFO - HTTP Request: POST http://kong:8000/rest/v1/prompts "HTTP/1.1 201 Created"
backend-core                    | INFO:     192.168.65.1:24526 - "POST /prompts HTTP/1.1" 200 OK
backend-core                    | INFO:     192.168.65.1:24526 - "OPTIONS /brains/ HTTP/1.1" 200 OK
supabase-kong                   | 172.19.0.8 - - [02/Dec/2023:10:41:19 +0000] "GET /rest/v1/brains_users?select=id%3Abrain_id%2C%20rights%2C%20brains%20%28brain_id%2C%20name%2C%20status%2C%20brain_type%29&user_id=eq.6f7f79d5-895d-4efc-a540-4e75b947eb25 HTTP/1.1" 401 52 "-" "python-httpx/0.24.1"
backend-core                    | 2023-12-02 10:41:19,568:INFO - HTTP Request: GET http://kong:8000/rest/v1/brains_users?select=id%3Abrain_id%2C%20rights%2C%20brains%20%28brain_id%2C%20name%2C%20status%2C%20brain_type%29&user_id=eq.6f7f79d5-895d-4efc-a540-4e75b947eb25 "HTTP/1.1 401 Unauthorized"
backend-core                    | INFO:     192.168.65.1:24527 - "POST /brains/ HTTP/1.1" 500 Internal Server Error
backend-core                    | ERROR:    Exception in ASGI application
backend-core                    | Traceback (most recent call last):
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core                    |     result = await app(  # type: ignore[func-returns-value]
backend-core                    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core                    |     return await self.app(scope, receive, send)
backend-core                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core                    |     await super().__call__(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core                    |     await self.middleware_stack(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core                    |     raise exc
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core                    |     await self.app(scope, receive, _send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core                    |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core                    |     await self.app(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core                    |     raise exc
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core                    |     await self.app(scope, receive, sender)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core                    |     raise e
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core                    |     await self.app(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core                    |     await route.handle(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core                    |     await self.app(scope, receive, send)
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core                    |     response = await func(request)
backend-core                    |                ^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core                    |     raw_response = await run_endpoint_function(
backend-core                    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core                    |     return await dependant.call(**values)
backend-core                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/code/routes/brain_routes.py", line 83, in create_new_brain
backend-core                    |     user_brains = brain_user_service.get_user_brains(current_user.id)
backend-core                    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/code/modules/brain/service/brain_user_service.py", line 120, in get_user_brains
backend-core                    |     results = self.brain_user_repository.get_user_brains(user_id)  # type: ignore
backend-core                    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core                    |   File "/code/modules/brain/repository/brains_users.py", line 23, in get_user_brains
backend-core                    |     .execute()
backend-core                    |      ^^^^^^^^^
backend-core                    |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 70, in execute
backend-core                    |     raise APIError(r.json())
backend-core                    | postgrest.exceptions.APIError: {'message': 'Invalid authentication credentials'}
```

**Comment by bradennapier** [comment]
The logs here show a similar error but it seems the logs are when calling /brains, I got same error when calling /prompts as well.
