### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by toddbenney** [StanGirard/quivr#1827]
### What happened?

I ran the new 60 second set up. Everything was working as normal. I was able to upload documents and chat with them. I was also able to create brains and everything was working nicely. After 15 minutes this all changed. I am now no longer able to chat with the bot and my brains that I created have dissapeared. I can't create new brains as well.

This is the error message I get in my terminal when I launch localhost:3000

Please let me know what is happening to cause this error
<img width="1202" alt="Screenshot 2023-12-05 at 21 19 01" src="https://github.com/StanGirard/quivr/assets/152516317/b8281df2-6d22-496a-9558-bf584b34c9ba">

### Relevant log output

```bash
[TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
```

**Comment by toddbenney** [comment]
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             | TypeError: fetch failed
web                             |     at Object.fetch (node:internal/deps/undici/undici:11730:11)
web                             |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web                             |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web                             |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
web                             |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
web                             |     errno: -111,
web                             |     code: 'ECONNREFUSED',
web                             |     syscall: 'connect',
web                             |     address: '127.0.0.1',
web                             |     port: 8000
web                             |   }
web                             | }
web                             | AuthRetryableFetchError: fetch failed
web                             |     at _handleRequest (/app/.next/server/chunks/191.js:44081:15)
web                             |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web                             |     at async _request (/app/.next/server/chunks/191.js:44063:18)
web                             |     at async /app/.next/server/chunks/191.js:43157:24
web                             |     at async /app/.next/server/chunks/191.js:44399:36 {
web                             |   __isAuthError: true,
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
supabase-kong                   | 192.168.65.1 - - [05/Dec/2023:21:32:44 +0000] "OPTIONS /auth/v1/token?grant_type=refresh_token HTTP/1.1" 200 0 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
supabase-auth                   | {"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","time":"2023-12-05T21:32:44Z","timestamp":"2023-12-05T21:32:44Z"}
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
supabase-auth                   | {"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"token","metering":true,"msg":"Login","time":"2023-12-05T21:32:44Z","user_id":"bce0d2e2-5de9-4f7e-9faf-90bab74c6d35"}
supabase-auth                   | {"auth_event":{"action":"token_revoked","actor_id":"bce0d2e2-5de9-4f7e-9faf-90bab74c6d35","actor_username":"toddbenney@davidhaye.com","actor_via_sso":false,"log_type":"token"},"component":"api","duration":128573583,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","status":200,"time":"2023-12-05T21:32:44Z","timestamp":"2023-12-05T21:32:44Z"}
supabase-kong                   | 192.168.65.1 - - [05/Dec/2023:21:32:44 +0000] "POST /auth/v1/token?grant_type=refresh_token HTTP/1.1" 200 1504 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }


> _🤖_
> 
> Hello @toddbenney! 👋
> 
> I'm [Dosu](https://dosu.dev), an AI bot here to help you with your issues, answer your questions, and guide you in contributing to the Quivr project. While we wait for a human maintainer, I'll be working on identifying the issue you're experiencing. Just hang tight, I'll provide a full answer shortly.

web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             | TypeError: fetch failed
web                             |     at Object.fetch (node:internal/deps/undici/undici:11730:11)
web                             |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web                             |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web                             |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
web                             |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
web                             |     errno: -111,
web                             |     code: 'ECONNREFUSED',
web                             |     syscall: 'connect',
web                             |     address: '127.0.0.1',
web                             |     port: 8000
web                             |   }
web                             | }
web                             | AuthRetryableFetchError: fetch failed
web                             |     at _handleRequest (/app/.next/server/chunks/191.js:44081:15)
web                             |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web                             |     at async _request (/app/.next/server/chunks/191.js:44063:18)
web                             |     at async /app/.next/server/chunks/191.js:43157:24
web                             |     at async /app/.next/server/chunks/191.js:44399:36 {
web                             |   __isAuthError: true,
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
supabase-kong                   | 192.168.65.1 - - [05/Dec/2023:21:32:44 +0000] "OPTIONS /auth/v1/token?grant_type=refresh_token HTTP/1.1" 200 0 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
supabase-auth                   | {"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","time":"2023-12-05T21:32:44Z","timestamp":"2023-12-05T21:32:44Z"}
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
supabase-auth                   | {"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"token","metering":true,"msg":"Login","time":"2023-12-05T21:32:44Z","user_id":"bce0d2e2-5de9-4f7e-9faf-90bab74c6d35"}
supabase-auth                   | {"auth_event":{"action":"token_revoked","actor_id":"bce0d2e2-5de9-4f7e-9faf-90bab74c6d35","actor_username":"toddbenney@davidhaye.com","actor_via_sso":false,"log_type":"token"},"component":"api","duration":128573583,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","status":200,"time":"2023-12-05T21:32:44Z","timestamp":"2023-12-05T21:32:44Z"}
supabase-kong                   | 192.168.65.1 - - [05/Dec/2023:21:32:44 +0000] "POST /auth/v1/token?grant_type=refresh_token HTTP/1.1" 200 1504 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }
web                             |  [TypeError: fetch failed] {
web                             |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:8000] {
web                             |   errno: -111,
web                             |   code: 'ECONNREFUSED',
web                             |   syscall: 'connect',
web                             |   address: '127.0.0.1',
web                             |   port: 8000
web                             | }
web                             | }
web                             |  [AuthRetryableFetchError: fetch failed] {
web                             |   __isAuthError: true,
web                             |   name: 'AuthRetryableFetchError',
web                             |   status: 0
web                             | }

**Comment by toddbenney** [comment]
Hi,

I have tried the steps below and nothing has worked.


  1.  I have checked and the server is running:

http://127.0.0.1:8000.

supabase-imgproxy               | INFO    [2023-12-06T13:33:47Z] Started /health  request_id=V5FYONAwhSw0hw7d4hrCB method=GET client_ip=127.0.0.1

supabase-imgproxy               | INFO    [2023-12-06T13:33:47Z] Completed in 1.22575ms /health  request_id=V5FYONAwhSw0hw7d4hrCB method=GET status=200 client_ip=127.0.0.1

supabase-imgproxy               | INFO    [2023-12-06T13:33:52Z] Started /health  request_id=vCrdOPjxr2KamALNihKxB method=GET client_ip=127.0.0.1

supabase-imgproxy               | INFO    [2023-12-06T13:33:52Z] Completed in 1.943541ms /health  request_id=vCrdOPjxr2KamALNihKxB method=GET status=200 client_ip=127.0.0.1


2. I temporarily disabled the firewall and same result. My settings allow new connections to be made so i don't think this is where the issue lies.


supabase-kong                   | 192.168.65.1 - - [06/Dec/2023:13:37:54 +0000] "OPTIONS /auth/v1/token?grant_type=password HTTP/1.1" 200 0 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"

supabase-auth                   | {"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","time":"2023-12-06T13:37:54Z","timestamp":"2023-12-06T13:37:54Z"}

supabase-auth                   | {"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"password","metering":true,"msg":"Login","time":"2023-12-06T13:37:54Z","user_id":"bce0d2e2-5de9-4f7e-9faf-90bab74c6d35"}

supabase-auth                   | ***@***.***","actor_via_sso":false,"log_type":"account","traits":{"provider":"email"}},"component":"api","duration":307981584,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"http://localhost:3000/","remote_addr":"192.168.65.1","status":200,"time":"2023-12-06T13:37:54Z","timestamp":"2023-12-06T13:37:54Z"}

supabase-kong                   | 192.168.65.1 - - [06/Dec/2023:13:37:54 +0000] "POST /auth/v1/token?grant_type=password HTTP/1.1" 200 1507 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"

3. I don't care about the missing brains, for now I want to be able to actually have a chat with the bot which i can't



[cid:f179ed5c-14a8-4a39-ac06-319d487d31aa]
Todd Benney

Assistant

[mobilePhone]
07470176960
[emailAddress]
***@***.***
[address]
Berkeley Suite, 35 Berkeley Square, London, W1J 5BF

________________________________

**Comment by toddbenney** [comment]
Sorry i misunderstood what you were saying.

How do i do this: If the application is indeed supposed to connect to a service on port 8000, you need to ensure that the service is running and accepting connections on that port.

[cid:78ad3b53-9713-42a9-aa8e-55e39d991ce2]
Todd Benney

Assistant

[mobilePhone]
07470176960
[emailAddress]
***@***.***
[address]
Berkeley Suite, 35 Berkeley Square, London, W1J 5BF

________________________________
