### ISSUE TITLE
Failed to upload file: AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by ronaldlee537** [StanGirard/quivr#187]
since i install, i never manage toi upload document or scrap url, i got immidiately this error on screen: Failed to upload file: AxiosError: Request failed with status code 500

and in log:

- error Error [TypeError]: action is not a function
web      |     at /app/node_modules/next/dist/server/app-render/action-handler.js:233:35
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      |     at async handleAction (/app/node_modules/next/dist/server/app-render/action-handler.js:170:13)
web      |     at async wrappedRender (/app/node_modules/next/dist/server/app-render/app-render.js:981:37)
web      |     at async doRender (/app/node_modules/next/dist/server/base-server.js:1031:34)
web      |     at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:1162:28)
web      |     at async /app/node_modules/next/dist/server/response-cache/index.js:99:36 {
web      |   digest: undefined

**Comment by caolixiang** [comment]
so am I

**Comment by xiaoxuan220** [comment]
so am I,How to fix it?

**Comment by jm-rizkallah** [comment]
@ronaldlee537 did you manage to solve that?
