### ISSUE TITLE
[Bug]: can not create document vector

### ISSUE THREAD

**Issue by permanzh** [StanGirard/quivr#2003]
### What happened?

I run quivr with local ollama, upload document to brain, can not see and vector record in supabase.
Got following error messages. It seems the same error with version 0.0.152 and 0.0.161. Is there any configuration for this issue or a bug?

### Relevant log output

```bash
worker        | 2024-01-10 05:21:12,641 [ERROR] packages.embeddings.vectors: Error creating vector for document Error raised by inference API HTTP code: 504, <html>
worker        | <head><title>504 Gateway Time-out</title></head>
worker        | <body>
worker        | <center><h1>504 Gateway Time-out</h1></center>
worker        | <hr><center>nginx/1.20.1</center>
worker        | </body>
worker        | </html>
worker        | 
worker        | [2024-01-10 05:21:12,653: WARNING/ForkPoolWorker-16] Error processing file: 'NoneType' object is not iterable
worker        | [2024-01-10 05:21:12,686: INFO/ForkPoolWorker-16] HTTP Request: PATCH http://192.168.20.27:54321/rest/v1/notifications?id=eq.3be760a6-f8f1-493e-80b9-d45dd3c9ae2c "HTTP/1.1 200 OK"
worker        | [2024-01-10 05:21:12,691: INFO/ForkPoolWorker-16] HTTP Request: PATCH http://192.168.20.27:54321/rest/v1/notifications?id=eq.3be760a6-f8f1-493e-80b9-d45dd3c9ae2c "HTTP/1.1 200 OK"
worker        | [2024-01-10 05:21:12,695: WARNING/ForkPoolWorker-16] --- Logging error ---
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16] Traceback (most recent call last):
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/code/celery_worker.py", line 109, in process_file_and_notify
worker        |     notification_service.update_notification_by_id(
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/code/modules/notification/service/notification_service.py", line 48, in update_notification_by_id
worker        |     return self.repository.update_notification_by_id(notification_id, notification)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/code/modules/notification/repository/notifications.py", line 38, in update_notification_by_id
worker        |     raise HTTPException(404, "Notification not found")
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16] fastapi.exceptions.HTTPException: (404, 'Notification not found')
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16] 
worker        | During handling of the above exception, another exception occurred:
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16] Traceback (most recent call last):
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
worker        |     R = retval = fun(*args, **kwargs)
worker        |                  ^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
worker        |     return self.run(*args, **kwargs)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,696: WARNING/ForkPoolWorker-16]   File "/code/celery_worker.py", line 128, in process_file_and_notify
worker        |     notification_service.update_notification_by_id(
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/code/modules/notification/service/notification_service.py", line 48, in update_notification_by_id
worker        |     return self.repository.update_notification_by_id(notification_id, notification)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/code/modules/notification/repository/notifications.py", line 38, in update_notification_by_id
worker        |     raise HTTPException(404, "Notification not found")
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16] fastapi.exceptions.HTTPException: (404, 'Notification not found')
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16] 
worker        | During handling of the above exception, another exception occurred:
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16] Traceback (most recent call last):
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
worker        |     msg = self.format(record)
worker        |           ^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
worker        |     return fmt.format(record)
worker        |            ^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
worker        |     msg = super().format(record)
worker        |           ^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/logging/__init__.py", line 695, in format
worker        |     record.exc_text = self.formatException(record.exc_info)
worker        |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
worker        |     r = super().formatException(ei)
worker        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/logging/__init__.py", line 645, in formatException
worker        |     traceback.print_exception(ei[0], ei[1], tb, None, sio)
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/traceback.py", line 124, in print_exception
worker        |     te = TracebackException(type(value), value, tb, limit=limit, compact=True)
worker        |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/traceback.py", line 702, in __init__
worker        |     self.stack = StackSummary._extract_from_extended_frame_gen(
worker        |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
worker        |     for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
worker        |     positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
worker        |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/traceback.py", line 366, in _get_code_position
worker        |     positions_gen = code.co_positions()
worker        |                     ^^^^^^^^^^^^^^^^^
worker        | [2024-01-10 05:21:12,697: WARNING/ForkPoolWorker-16] AttributeError: '_Code' object has no attribute 'co_positions'
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16] Call stack:
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/bin/celery", line 8, in <module>
worker        |     sys.exit(main())
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
worker        |     sys.exit(_main())
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
worker        |     return celery(auto_envvar_prefix="CELERY")
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
worker        |     return self.main(*args, **kwargs)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
worker        |     rv = self.invoke(ctx)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
worker        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
worker        |     return ctx.invoke(self.callback, **ctx.params)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
worker        |     return __callback(*args, **kwargs)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
worker        |     return f(get_current_context(), *args, **kwargs)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
worker        |     return f(ctx, *args, **kwargs)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
worker        |     worker.start()
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
worker        |     self.blueprint.start(self)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
worker        |     step.start(parent)
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
worker        |     return self.obj.start()
worker        | [2024-01-10 05:21:12,698: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
worker        |     self.on_start()
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
worker        |     P = self._pool = Pool(processes=self.limit,
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
worker        |     super().__init__(processes, *args, **kwargs)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
worker        |     self._create_worker_process(i)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
worker        |     return super()._create_worker_process(i)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
worker        |     w.start()
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 124, in start
worker        |     self._popen = self._Popen(self)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
worker        |     return Popen(process_obj)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
worker        |     self._launch(process_obj)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
worker        |     code = process_obj._bootstrap()
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
worker        |     self.run()
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/process.py", line 114, in run
worker        |     self._target(*self._args, **self._kwargs)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
worker        |     sys.exit(self.workloop(pid=pid))
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
worker        |     result = (True, prepare_result(fun(*args, **kwargs)))
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
worker        |     R, I, T, Rstr = tasks[task].__trace__(
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
worker        |     I, R, state, retval = on_error(task_request, exc, uuid)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
worker        |     R = I.handle_error_state(
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
worker        |     return {
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
worker        |     self._log_error(task, req, einfo)
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
worker        |     logger.log(policy.severity, policy.format.strip(), context,
worker        | [2024-01-10 05:21:12,699: WARNING/ForkPoolWorker-16] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
worker        | Arguments: {'hostname': 'celery@f14fd4e7d57b', 'id': 'ef198d92-c29b-4432-913a-62b3b9fde875', 'name': 'process_file_and_notify', 'exc': "HTTPException(status_code=404, detail='Notification not found')", 'traceback': 'Traceback (most recent call last):\n  File "/code/celery_worker.py", line 109, in process_file_and_notify\n    notification_service.update_notification_by_id(\n  File "/code/modules/notification/service/notification_service.py", line 48, in update_notification_by_id\n    return self.repository.update_notification_by_id(notification_id, notification)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/code/modules/notification/repository/notifications.py", line 38, in update_notification_by_id\n    raise HTTPException(404, "Notification not found")\nfastapi.exceptions.HTTPException: (404, \'Notification not found\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/code/celery_worker.py", line 128, in process_file_and_notify\n    notification_service.update_notification_by_id(\n  File "/code/modules/notification/service/notification_service.py", line 48, in update_notification_by_id\n    return self.repository.update_notification_by_id(notification_id, notification)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/code/modules/notification/repository/notifications.py", line 38, in update_notification_by_id\n    raise HTTPException(404, "Notification not found")\nfastapi.exceptions.HTTPException: (404, \'Notification not found\')\n', 'args': '[]', 'kwargs': "{'file_name': '408451d4-0212-4eb8-9a6e-c696969cb3c6/supbase.txt', 'file_original_name': 'supbase.txt', 'brain_id': UUID('408451d4-0212-4eb8-9a6e-c696969cb3c6'), 'notification_id': UUID('3be760a6-f8f1-493e-80b9-d45dd3c9ae2c')}", 'description': 'raised unexpected', 'internal': False}
```

**Comment by permanzh** [comment]
@dosu-bot  Does quivr use llm to create the document vecotr? if i run local llm, it means quvir will call ollama to create document vectors?
