### ISSUE TITLE
Stuck at Please wait

### ISSUE THREAD

**Issue by jairodriguez** [StanGirard/quivr#25]
The browser shows "PLEASE WAIT "  indefinetly. Any ideas? All dependencies installed correctly, ran table creation script in supabase successfully, tried credentials in secrets.toml with and without quotes.
<img width="993" alt="Screenshot 2023-05-15 at 18 50 35" src="https://github.com/StanGirard/quivr/assets/73152066/8fe01b55-63f2-404b-89f9-13b6477a443d">

**Comment by StanGirard** [comment]
Can you give me the logs @jairodriguez  ?

**Comment by jairodriguez** [comment]
This si the gist of it:
2023-05-15 20:20:29.393 Uncaught exception
Traceback (most recent call last):
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py", line 268, in finish
    self.delegate.finish()
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 2290, in finish
    self.execute()
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 2309, in execute
    self.handler = self.handler_class(
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py", line 224, in __init__
    super().__init__(application, request, **kwargs)
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 209, in __init__
    super().__init__()
  File "/Users/bernardojrodriguez/opt/anaconda3/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated

I installed python 3.8 and reinstalled dependencies in virtual environment with the same results. Gpt4 was unable to help troubleshoot

**Comment by StanGirard** [comment]
Can you try with python 3.10 at least. I have 3.11 on my computer.

**Comment by jairodriguez** [comment]
Duh, now I see the higher than 3.10 on the readme. Thanks for the heads up. Now it works!
