### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory: '/code'

### ISSUE THREAD

**Issue by giuliastro** [StanGirard/quivr#287]
Hello,
I get the error in the subject. Everything starts correctly, but I can't login or register a new account.
Could it be related to this error? I don't think it's a RAM or storage problem since I have 16GB and 1TB.

Thank you in advance.

```
Traceback (most recent call last):
backend  |   File "/usr/local/bin/uvicorn", line 8, in <module>
backend  |     sys.exit(main())
backend  |              ^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
backend  |     return self.main(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
backend  |     rv = self.invoke(ctx)
backend  |          ^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
backend  |     return ctx.invoke(self.callback, **ctx.params)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
backend  |     return __callback(*args, **kwargs)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
backend  |     run(
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 573, in run
backend  |     ChangeReload(config, target=server.run, sockets=[sock]).run()
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 50, in run
backend  |     for changes in self:
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 69, in __next__
backend  |     return self.should_restart()
backend  |            ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/supervisors/statreload.py", line 32, in should_restart
backend  |     for file in self.iter_py_files():
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/supervisors/statreload.py", line 52, in iter_py_files
backend  |     for path in list(reload_dir.rglob("*.py")):
backend  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/pathlib.py", line 968, in rglob
backend  |     for p in selector.select_from(self):
backend  |   File "/usr/local/lib/python3.11/pathlib.py", line 408, in _select_from
backend  |     for p in successor_select(starting_point, is_dir, exists, scandir):
backend  |   File "/usr/local/lib/python3.11/pathlib.py", line 356, in _select_from
backend  |     entries = list(scandir_it)
backend  |               ^^^^^^^^^^^^^^^^
backend  | OSError: [Errno 12] Cannot allocate memory: '/code'
```

**Comment by giuliastro** [comment]
Marking as solved. The login problem was related to Supabase.
For what it concerns the memory error, it just didn't appear any longer.
