### ISSUE TITLE
can not run in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by daibingfeng** [StanGirard/quivr#291]
Hi, I just installed the quivr in Ubuntu 22.04 LTS, when I use ***.***.***.**:3000, it display the wrong message below.

web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web      | Error [TypeError]: Invalid URL: XXXX/auth/v1
web      |     at new URLImpl (evalmachine.<anonymous>:2830:17)
web      |     at exports.setup (evalmachine.<anonymous>:3037:16)
web      |     at new URL (evalmachine.<anonymous>:3091:26)
web      |     at new SupabaseClient (file:///app/.next/server/middleware.js:9512:41)
web      |     at createClient (file:///app/.next/server/middleware.js:9670:12)
web      |     at createServerSupabaseClient (file:///app/.next/server/middleware.js:13363:10)
web      |     at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
web      |     at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
web      |     at adapter (file:///app/.next/server/middleware.js:1967:33)
web      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by daibingfeng** [comment]
I make a mistake, I didn't set the frontend/.env
sorry
