### ISSUE TITLE
[Issue] Creating Brain results in CORS Error

### ISSUE THREAD

**Issue by regenrek** [StanGirard/quivr#581]
Hi,

fresh install with Apple M1

![image](https://github.com/StanGirard/quivr/assets/5182020/02bec232-469d-4482-b369-6b7839c6ba49)

Any Ideas?

Logs:

```
backend  | INFO:     Will watch for changes in these directories: ['/code']
backend  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [7] using StatReload
web      | - info Loaded env from /app/.env
backend  | INFO:     Started server process [9]
backend  | INFO:     Waiting for application startup.
backend  | [INFO] Using already downloaded file pandoc-3.1.5-1-arm64.deb
backend  | 2023-07-10 08:34:58,652:INFO - Using already downloaded file pandoc-3.1.5-1-arm64.deb
backend  | [INFO] Unpacking pandoc-3.1.5-1-arm64.deb to tempfolder...
backend  | 2023-07-10 08:34:58,653:INFO - Unpacking pandoc-3.1.5-1-arm64.deb to tempfolder...
backend  | [INFO] Copying pandoc to /root/bin ...
backend  | 2023-07-10 08:35:00,832:INFO - Copying pandoc to /root/bin ...
backend  | [INFO] Making /root/bin/pandoc executeable...
backend  | 2023-07-10 08:35:00,903:INFO - Making /root/bin/pandoc executeable...
backend  | [INFO] Copying copyright to /root/bin ...
backend  | 2023-07-10 08:35:00,903:INFO - Copying copyright to /root/bin ...
backend  | INFO:     Application startup complete.
backend  | INFO:     172.19.0.1:61434 - "GET /brains/ HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend  |     return await dependant.call(**values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/routes/brain_routes.py", line 40, in brain_endpoint
backend  |     brains = brain.get_user_brains(current_user.id)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/models/brains.py", line 55, in get_user_brains
backend  |     .execute()
backend  |      ^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend  |     raise APIError(r.json())
backend  | postgrest.exceptions.APIError: {'code': 'PGRST200', 'details': "Searched for a foreign key relationship between 'brains_users' and 'brains' in the schema 'public', but no matches were found.", 'hint': None, 'message': "Could not find a relationship between 'brains_users' and 'brains' in the schema cache"}
backend  | INFO:     172.19.0.1:61436 - "GET /brains/default/ HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend  |     return await dependant.call(**values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/routes/brain_routes.py", line 58, in get_default_brain_endpoint
backend  |     default_brain = get_default_user_brain(current_user)
backend  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/models/brains.py", line 248, in get_default_user_brain
backend  |     .execute()
backend  |      ^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend  |     raise APIError(r.json())
backend  | postgrest.exceptions.APIError: {'code': '42P01', 'details': None, 'hint': None, 'message': 'relation "public.brains_users" does not exist'}
```

Regards

**Comment by grebett** [comment]
Same error with Intel Chip.
<img width="250" alt="Screenshot 2023-07-10 at 11 40 07" src="https://github.com/StanGirard/quivr/assets/5601555/ae2e9ce8-4211-4908-b3b7-6e1ff21694a9">

**Comment by grebett** [comment]
Duplicate of https://github.com/StanGirard/quivr/issues/559#issue-1794860745?

**Comment by StanGirard** [comment]
It means the backend doesn't work. You probably forgot to run the migrations ;)

**Comment by ziptron** [comment]
![image](https://github.com/StanGirard/quivr/assets/17092430/c969b055-244d-48f1-a1dc-479d48c8489c)

I get stuck running the migration.sh script at the point in the attached screen shot.

**Comment by johnfelipe** [comment]
any progress here?
https://www.youtube.com/watch?v=rFEbz93G9U8
soon i will test manually, not using helper script
if any put a PR for solve this pls share....

**Comment by ziptron** [comment]
I tried manually, still did not work.

**Comment by johnfelipe** [comment]
@ziptron do u use steps like in video?

**Comment by ziptron** [comment]
Yes, tried it twice.

**Comment by johnfelipe** [comment]
Ok, then i will wait
pls hurry up for solve this issue
is an issue for installation, then will be ensure a good effort for solve it

**Comment by ziptron** [comment]
So I solved this issue for myself. 

I had two problems. 

The biggest issue was that the backend was not running. I fixed this using (https://github.com/StanGirard/quivr/issues/556)
The next issue was Firefox. I still have issue running this in firefox, but I got it to run it Edge browser.

**Comment by ollieanwyll** [comment]
The issue for me was accessing via 0.0.0.0:3000 instead of localhost:3000

**Comment by johnfelipe** [comment]
> The issue for me was accessing via 0.0.0.0:3000 instead of localhost:3000

in chrome is possible do that?
