### ISSUE TITLE
Backend startup failed - ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#585]
2023-07-10 21:17:15 INFO:     Will watch for changes in these directories: ['/code']
2023-07-10 21:17:15 INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
2023-07-10 21:17:15 INFO:     Started reloader process [8] using StatReload
2023-07-10 21:17:32 INFO:     Started server process [10]
2023-07-10 21:17:32 INFO:     Waiting for application startup.
2023-07-10 21:17:32 ERROR:    Traceback (most recent call last):
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
2023-07-10 21:17:32     h.request(req.get_method(), req.selector, req.data, headers,
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
2023-07-10 21:17:32     self._send_request(method, url, body, headers, encode_chunked)
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
2023-07-10 21:17:32     self.endheaders(body, encode_chunked=encode_chunked)
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
2023-07-10 21:17:32     self._send_output(message_body, encode_chunked=encode_chunked)
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
2023-07-10 21:17:32     self.send(msg)
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 979, in send
2023-07-10 21:17:32     self.connect()
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 1451, in connect
2023-07-10 21:17:32     super().connect()
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/http/client.py", line 945, in connect
2023-07-10 21:17:32     self.sock = self._create_connection(
2023-07-10 21:17:32                 ^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2023-07-10 21:17:32     raise exceptions[0]
2023-07-10 21:17:32   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2023-07-10 21:17:32     sock.connect(sa)
2023-07-10 21:17:32 ConnectionRefusedError: [Errno 111] Connection refused

**Comment by georgeqin96** [comment]
any idea?
but I run below script I can retrieve data. why request.py connection failed?
import supabase

# config Supabase connect param
supabase_url = 'my-project url'
supabase_key = 'my-key'

#create Supabase client object
client = supabase.create_client(supabase_url, supabase_key)

# Define the table name
table_name = 'brains'

# Perform the select query
response = client.table('brains').select('*').execute()
print(response)

**Comment by georgeqin96** [comment]
nothing
