### ISSUE TITLE
 500 Internal Server Error, 502 error

### ISSUE THREAD

**Issue by pandaupc** [StanGirard/quivr#597]
Certainly, here is the complete transcription of the error:

I'm currently able to import files and provide regular answers. However, an error occurs when providing document-based answers. Upon investigation, the error seems to occur when fetching the context for computing similarity, specifically when calling the similarity interface of Supabase. The error message is as follows:

arduino
Copy code
INFO:     127.0.0.1:59312 - "POST /chat/ef77183d-85bb-4389-afe9-6d13dcc0237b/question?brain_id=242a3a9c-f0a5-4993-b9f1-44efdf22c2b4 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  ...
  File "/Users/huida/Applications/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/huida/code/quivr/backend/routes/chat_routes.py", line 197, in create_question_handler
    chat_answer = gpt_answer_generator.generate_answer(chat_question.question)
  File "/Users/huida/code/quivr/backend/llm/openai_functions.py", line 204, in generate_answer
    messages=self._construct_prompt(
  File "/Users/huida/code/quivr/backend/llm/openai_functions.py", line 158, in _construct_prompt
    chat_context = self._get_context(question)
  File "/Users/huida/code/quivr/backend/llm/openai_functions.py", line 128, in _get_context
    return self.vector_store.similarity_search(query=question)
  File "/Users/huida/code/quivr/backend/vectorstore/supabase.py", line 42, in similarity_search
    ).execute()
  File "/Users/huida/Applications/anaconda3/lib/python3.10/site-packages/postgrest/_sync/request_builder.py", line 55, in execute
    r = self.session.request(
  File "/Users/huida/Applications/anaconda3/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  ...
httpx.ReadTimeout: The read operation timed out
In the Supabase interface manager, a 502 error is displayed, but other interface calls are functioning normally.

**Comment by kuixiansheng** [comment]
The above method does not seem to work, ClientOption does not seem to support setting timeout, this step is currently missing

is there another way?
