### ISSUE TITLE
Has anyone managed to make it work on Ubuntu?

### ISSUE THREAD

**Issue by ioncandel** [StanGirard/quivr#703]
I have tried another browser in which to open locally quivr. With Brave Browser I get the following error:

ReferenceError: sessionStorage is not defined
at redirectToLogin (/app/.next/server/app/upload/page.js:969:5)
at useFileUploader (/app/.next/server/app/upload/page.js:728:51)
at FileUploader (/app/.next/server/app/upload/page.js:820:117)
at Je (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
at Ke (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
at Me (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
at Ke (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
at Je (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:215)

Has anyone managed to make it work on Ubuntu?

**Comment by ioncandel** [comment]
No issues with that, you might have issues with the Docker installation. Try to do it without Snap (use the tutorial on the Docker site).

**Comment by ioncandel** [comment]
So after digging some more I localized the source in the backend/core/auth/auth_bearer.py file line 41:

  return self.get_test_user()

then the line 54:

def get_test_user(self) -> User:
        return User(
            email="test@example.com", id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"  # type: ignore
        )  # replace with test user information 

How come this function is called when I try to connect on local????
