### ISSUE TITLE
[Issue]ERROR: Application startup failed. Exiting.

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#935]
2023-08-11 14:06:10 yarn run v1.22.19
2023-08-11 14:06:10 $ next start
2023-08-11 14:06:10 - ready started server on 0.0.0.0:3000, url: http://localhost:3000
2023-08-11 14:06:10 - info Loaded env from /app/.env
2023-08-11 14:07:53 i18next: languageChanged en
2023-08-11 14:07:53 i18next: initialized {
2023-08-11 14:07:53   debug: true,
2023-08-11 14:07:53   initImmediate: true,
2023-08-11 14:07:53   ns: [ 'translation' ],
2023-08-11 14:07:53   defaultNS: 'translation',
2023-08-11 14:07:53   fallbackLng: [ 'en' ],
2023-08-11 14:07:53   fallbackNS: false,
2023-08-11 14:07:53   supportedLngs: false,
2023-08-11 14:07:53   nonExplicitSupportedLngs: false,
2023-08-11 14:07:53   load: 'all',
2023-08-11 14:07:53   preload: false,
2023-08-11 14:07:53   simplifyPluralSuffix: true,
2023-08-11 14:07:53 react-i18next:: You will need to pass in an i18next instance by using initReactI18next
2023-08-11 14:07:53   keySeparator: '.',
2023-08-11 14:07:53   nsSeparator: ':',
2023-08-11 14:07:53   pluralSeparator: '_',
2023-08-11 14:07:53   contextSeparator: '_',
2023-08-11 14:07:53   partialBundledLanguages: false,
2023-08-11 14:07:53   saveMissing: false,
2023-08-11 14:07:53   updateMissing: false,
2023-08-11 14:07:53   saveMissingTo: 'fallback',
2023-08-11 14:07:53   saveMissingPlurals: true,
2023-08-11 14:07:53   missingKeyHandler: false,
2023-08-11 14:07:53   missingInterpolationHandler: false,
2023-08-11 14:07:53   postProcess: false,
2023-08-11 14:07:53   postProcessPassResolved: false,
2023-08-11 14:07:53   returnNull: false,
2023-08-11 14:07:53   returnEmptyString: true,
2023-08-11 14:07:53   returnObjects: false,
2023-08-11 14:07:53   joinArrays: false,
2023-08-11 14:07:53   returnedObjectHandler: false,
2023-08-11 14:07:53   parseMissingKeyHandler: false,
2023-08-11 14:07:53   appendNamespaceToMissingKey: false,
2023-08-11 14:07:53   appendNamespaceToCIMode: false,
2023-08-11 14:07:53   overloadTranslationOptionHandler: [Function: handle],
2023-08-11 14:07:53   interpolation: {
2023-08-11 14:07:53     escapeValue: true,
2023-08-11 14:07:53     format: [Function: bound format],
2023-08-11 14:07:53     prefix: '{{',
2023-08-11 14:07:53     suffix: '}}',
2023-08-11 14:07:53     formatSeparator: ',',
2023-08-11 14:07:53     unescapePrefix: '-',
2023-08-11 14:07:53     nestingPrefix: '$t(',
2023-08-11 14:07:53     nestingSuffix: ')',
2023-08-11 14:07:53     nestingOptionsSeparator: ',',
2023-08-11 14:07:53     maxReplaces: 1000,
2023-08-11 14:07:53     skipOnVariables: true
2023-08-11 14:07:53   },
2023-08-11 14:07:53   lng: 'en',
2023-08-11 14:07:53   resources: {
2023-08-11 14:07:53     en: {
2023-08-11 14:07:53       brain: [Object],
2023-08-11 14:07:53       chat: [Object],
2023-08-11 14:07:53       config: [Object],
2023-08-11 14:07:53       explore: [Object],
2023-08-11 14:07:53       invitation: [Object],
2023-08-11 14:07:53       login: [Object],
2023-08-11 14:07:53       logout: [Object],
2023-08-11 14:07:53       signUp: [Object],
2023-08-11 14:07:53       translation: [Object],
2023-08-11 14:07:53       updatePassword: [Object],
2023-08-11 14:07:53       upload: [Object],
2023-08-11 14:07:53       user: [Object],
2023-08-11 14:07:53       delete_brain: [Object]
2023-08-11 14:07:53     },
2023-08-11 14:07:53     es: {
2023-08-11 14:07:53       brain: [Object],
2023-08-11 14:07:53       chat: [Object],
2023-08-11 14:07:53       config: [Object],
2023-08-11 14:07:53       explore: [Object],
2023-08-11 14:07:53       invitation: [Object],
2023-08-11 14:07:53       login: [Object],
2023-08-11 14:07:53       logout: [Object],
2023-08-11 14:07:53       signUp: [Object],
2023-08-11 14:07:53       translation: [Object],
2023-08-11 14:07:53       updatePassword: [Object],
2023-08-11 14:07:53       upload: [Object],
2023-08-11 14:07:53       user: [Object],
2023-08-11 14:07:53       delete_brain: [Object]
2023-08-11 14:07:53     },
2023-08-11 14:07:53     fr: {
2023-08-11 14:07:53       brain: [Object],
2023-08-11 14:07:53       chat: [Object],
2023-08-11 14:07:53       config: [Object],
2023-08-11 14:07:53       explore: [Object],
2023-08-11 14:07:53       invitation: [Object],
2023-08-11 14:07:53       login: [Object],
2023-08-11 14:07:53       logout: [Object],
2023-08-11 14:07:53       signUp: [Object],
2023-08-11 14:07:53       translation: [Object],
2023-08-11 14:07:53       updatePassword: [Object],
2023-08-11 14:07:53       upload: [Object],
2023-08-11 14:07:53       user: [Object],
2023-08-11 14:07:53       delete_brain: [Object]
2023-08-11 14:07:53     },
2023-08-11 14:07:53     ru: {
2023-08-11 14:07:53       brain: [Object],
2023-08-11 14:07:53       chat: [Object],
2023-08-11 14:07:53       config: [Object],
2023-08-11 14:07:53       explore: [Object],
2023-08-11 14:07:53       invitation: [Object],
2023-08-11 14:07:53       login: [Object],
2023-08-11 14:07:53       logout: [Object],
2023-08-11 14:07:53       signUp: [Object],
2023-08-11 14:07:53       translation: [Object],
2023-08-11 14:07:53       updatePassword: [Object],
2023-08-11 14:07:53       upload: [Object],
2023-08-11 14:07:53       user: [Object],
2023-08-11 14:07:53       delete_brain: [Object]
2023-08-11 14:07:53     }
2023-08-11 14:07:53   },
2023-08-11 14:07:53   ignoreJSONStructure: true
2023-08-11 14:07:53 }
2023-08-11 19:38:43 yarn run v1.22.19
2023-08-11 19:38:43 $ next start
2023-08-11 19:38:44 - ready started server on 0.0.0.0:3000, url: http://localhost:3000
2023-08-11 19:38:45 - info Loaded env from /app/.env
2023-08-11 19:39:42 i18next: languageChanged en
2023-08-11 19:39:42 i18next: initialized {
2023-08-11 19:39:42   debug: true,
2023-08-11 19:39:42   initImmediate: true,
2023-08-11 19:39:42   ns: [ 'translation' ],
2023-08-11 19:39:42   defaultNS: 'translation',
2023-08-11 19:39:42   fallbackLng: [ 'en' ],
2023-08-11 19:39:42   fallbackNS: false,
2023-08-11 19:39:42   supportedLngs: false,
2023-08-11 19:39:42   nonExplicitSupportedLngs: false,
2023-08-11 19:39:42   load: 'all',
2023-08-11 19:39:42   preload: false,
2023-08-11 19:39:42   simplifyPluralSuffix: true,
2023-08-11 19:39:42   keySeparator: '.',
2023-08-11 19:39:42   nsSeparator: ':',
2023-08-11 19:39:42   pluralSeparator: '_',
2023-08-11 19:39:42   contextSeparator: '_',
2023-08-11 19:39:42   partialBundledLanguages: false,
2023-08-11 19:39:42   saveMissing: false,
2023-08-11 19:39:42   updateMissing: false,
2023-08-11 19:39:42   saveMissingTo: 'fallback',
2023-08-11 19:39:42   saveMissingPlurals: true,
2023-08-11 19:39:42   missingKeyHandler: false,
2023-08-11 19:39:42   missingInterpolationHandler: false,
2023-08-11 19:39:42   postProcess: false,
2023-08-11 19:39:42   postProcessPassResolved: false,
2023-08-11 19:39:42   returnNull: false,
2023-08-11 19:39:42   returnEmptyString: true,
2023-08-11 19:39:42   returnObjects: false,
2023-08-11 19:39:42   joinArrays: false,
2023-08-11 19:39:42   returnedObjectHandler: false,
2023-08-11 19:39:42   parseMissingKeyHandler: false,
2023-08-11 19:39:42   appendNamespaceToMissingKey: false,
2023-08-11 19:39:42   appendNamespaceToCIMode: false,
2023-08-11 19:39:42   overloadTranslationOptionHandler: [Function: handle],
2023-08-11 19:39:42   interpolation: {
2023-08-11 19:39:42     escapeValue: true,
2023-08-11 19:39:42     format: [Function: bound format],
2023-08-11 19:39:42     prefix: '{{',
2023-08-11 19:39:42     suffix: '}}',
2023-08-11 19:39:42     formatSeparator: ',',
2023-08-11 19:39:42     unescapePrefix: '-',
2023-08-11 19:39:42     nestingPrefix: '$t(',
2023-08-11 19:39:42     nestingSuffix: ')',
2023-08-11 19:39:42     nestingOptionsSeparator: ',',
2023-08-11 19:39:42     maxReplaces: 1000,
2023-08-11 19:39:42     skipOnVariables: true
2023-08-11 19:39:42   },
2023-08-11 19:39:42   lng: 'en',
2023-08-11 19:39:42   resources: {
2023-08-11 19:39:42     en: {
2023-08-11 19:39:42       brain: [Object],
2023-08-11 19:39:42       chat: [Object],
2023-08-11 19:39:42       config: [Object],
2023-08-11 19:39:42       explore: [Object],
2023-08-11 19:39:42       invitation: [Object],
2023-08-11 19:39:42       login: [Object],
2023-08-11 19:39:42       logout: [Object],
2023-08-11 19:39:42       signUp: [Object],
2023-08-11 19:39:42       translation: [Object],
2023-08-11 19:39:42       updatePassword: [Object],
2023-08-11 19:39:42       upload: [Object],
2023-08-11 19:39:42       user: [Object],
2023-08-11 19:39:42       delete_brain: [Object]
2023-08-11 19:39:42     },
2023-08-11 19:39:42     es: {
2023-08-11 19:39:42       brain: [Object],
2023-08-11 19:39:42       chat: [Object],
2023-08-11 19:39:42       config: [Object],
2023-08-11 19:39:42       explore: [Object],
2023-08-11 19:39:42       invitation: [Object],
2023-08-11 19:39:42       login: [Object],
2023-08-11 19:39:42       logout: [Object],
2023-08-11 19:39:42 react-i18next:: You will need to pass in an i18next instance by using initReactI18next
2023-08-11 19:39:42       signUp: [Object],
2023-08-11 19:39:42       translation: [Object],
2023-08-11 19:39:42       updatePassword: [Object],
2023-08-11 19:39:42       upload: [Object],
2023-08-11 19:39:42       user: [Object],
2023-08-11 19:39:42       delete_brain: [Object]
2023-08-11 19:39:42     },
2023-08-11 19:39:42     fr: {
2023-08-11 19:39:42       brain: [Object],
2023-08-11 19:39:42       chat: [Object],
2023-08-11 19:39:42       config: [Object],
2023-08-11 19:39:42       explore: [Object],
2023-08-11 19:39:42       invitation: [Object],
2023-08-11 19:39:42       login: [Object],
2023-08-11 19:39:42       logout: [Object],
2023-08-11 19:39:42       signUp: [Object],
2023-08-11 19:39:42       translation: [Object],
2023-08-11 19:39:42       updatePassword: [Object],
2023-08-11 19:39:42       upload: [Object],
2023-08-11 19:39:42       user: [Object],
2023-08-11 19:39:42       delete_brain: [Object]
2023-08-11 19:39:42     },
2023-08-11 19:39:42     ru: {
2023-08-11 19:39:42       brain: [Object],
2023-08-11 19:39:42       chat: [Object],
2023-08-11 19:39:42       config: [Object],
2023-08-11 19:39:42       explore: [Object],
2023-08-11 19:39:42       invitation: [Object],
2023-08-11 19:39:42       login: [Object],
2023-08-11 19:39:42       logout: [Object],
2023-08-11 19:39:42       signUp: [Object],
2023-08-11 19:39:42       translation: [Object],
2023-08-11 19:39:42       updatePassword: [Object],
2023-08-11 19:39:42       upload: [Object],
2023-08-11 19:39:42       user: [Object],
2023-08-11 19:39:42       delete_brain: [Object]
2023-08-11 19:39:42     }
2023-08-11 19:39:42   },
2023-08-11 19:39:42   ignoreJSONStructure: true
2023-08-11 19:39:42 }

2023-08-11 14:17:46 WARNING: Package(s) not found: gpt4all
2023-08-11 14:17:46 INFO:     Will watch for changes in these directories: ['/code']
2023-08-11 14:17:46 INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
2023-08-11 14:17:46 INFO:     Started reloader process [8] using StatReload
2023-08-11 14:17:49 INFO:     Started server process [10]
2023-08-11 14:17:49 INFO:     Waiting for application startup.
2023-08-11 14:17:52 [INFO] Using already downloaded file pandoc-3.1.6.1-1-arm64.deb
2023-08-11 14:17:52 2023-08-11 06:17:52,566:INFO - Using already downloaded file pandoc-3.1.6.1-1-arm64.deb
2023-08-11 14:17:52 [INFO] Unpacking pandoc-3.1.6.1-1-arm64.deb to tempfolder...
2023-08-11 14:17:52 2023-08-11 06:17:52,566:INFO - Unpacking pandoc-3.1.6.1-1-arm64.deb to tempfolder...
2023-08-11 14:17:52 ar: /code/pandoc-3.1.6.1-1-arm64.deb is not a valid archive
2023-08-11 14:17:52 ERROR:    Traceback (most recent call last):
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2023-08-11 14:17:52     async with self.lifespan_context(app) as maybe_state:
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
2023-08-11 14:17:52     await self._router.startup()
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
2023-08-11 14:17:52     await handler()
2023-08-11 14:17:52   File "/code/main.py", line 42, in startup_event
2023-08-11 14:17:52     pypandoc.download_pandoc()
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 267, in download_pandoc
2023-08-11 14:17:52     unpack(filename, targetfolder)
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 95, in _handle_linux
2023-08-11 14:17:52     subprocess.check_call(cmd)
2023-08-11 14:17:52   File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
2023-08-11 14:17:52     raise CalledProcessError(retcode, cmd)
2023-08-11 14:17:52 subprocess.CalledProcessError: Command '['ar', 'x', '/code/pandoc-3.1.6.1-1-arm64.deb']' returned non-zero exit status 1.
2023-08-11 14:17:52 
2023-08-11 14:17:52 ERROR:    Application startup failed. Exiting.
2023-08-11 19:38:45 WARNING: Package(s) not found: gpt4all
2023-08-11 19:38:45 INFO:     Will watch for changes in these directories: ['/code']
2023-08-11 19:38:45 INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
2023-08-11 19:38:45 INFO:     Started reloader process [8] using StatReload
2023-08-11 19:38:49 INFO:     Started server process [10]
2023-08-11 19:38:49 INFO:     Waiting for application startup.
2023-08-11 19:40:58 ERROR:    Traceback (most recent call last):
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2023-08-11 19:40:58     async with self.lifespan_context(app) as maybe_state:
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
2023-08-11 19:40:58     await self._router.startup()
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
2023-08-11 19:40:58     await handler()
2023-08-11 19:40:58   File "/code/main.py", line 42, in startup_event
2023-08-11 19:40:58     pypandoc.download_pandoc()
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 231, in download_pandoc
2023-08-11 19:40:58     pandoc_urls, _ = _get_pandoc_urls(version)
2023-08-11 19:40:58                      ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 49, in _get_pandoc_urls
2023-08-11 19:40:58     response = urlopen(url)
2023-08-11 19:40:58                ^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
2023-08-11 19:40:58     return opener.open(url, data, timeout)
2023-08-11 19:40:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
2023-08-11 19:40:58     response = meth(req, response)
2023-08-11 19:40:58                ^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
2023-08-11 19:40:58     response = self.parent.error(
2023-08-11 19:40:58                ^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 557, in error
2023-08-11 19:40:58     result = self._call_chain(*args)
2023-08-11 19:40:58              ^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
2023-08-11 19:40:58     result = func(*args)
2023-08-11 19:40:58              ^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 749, in http_error_302
2023-08-11 19:40:58     return self.parent.open(new, timeout=req.timeout)
2023-08-11 19:40:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
2023-08-11 19:40:58     response = self._open(req, data)
2023-08-11 19:40:58                ^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
2023-08-11 19:40:58     result = self._call_chain(self.handle_open, protocol, protocol +
2023-08-11 19:40:58              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
2023-08-11 19:40:58     result = func(*args)
2023-08-11 19:40:58              ^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
2023-08-11 19:40:58     return self.do_open(http.client.HTTPSConnection, req,
2023-08-11 19:40:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/urllib/request.py", line 1352, in do_open
2023-08-11 19:40:58     r = h.getresponse()
2023-08-11 19:40:58         ^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
2023-08-11 19:40:58     response.begin()
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
2023-08-11 19:40:58     version, status, reason = self._read_status()
2023-08-11 19:40:58                               ^^^^^^^^^^^^^^^^^^^
2023-08-11 19:40:58   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
2023-08-11 19:40:58     raise RemoteDisconnected("Remote end closed connection without"
2023-08-11 19:40:58 http.client.RemoteDisconnected: Remote end closed connection without response
2023-08-11 19:40:58 
2023-08-11 19:40:58 ERROR:    Application startup failed. Exiting.

**Comment by hyg290** [comment]
i have same issue.pandoc_download error,is china network problem?
