### ISSUE TITLE
[Issue] Install error

### ISSUE THREAD

**Issue by heywalter** [StanGirard/quivr#949]
Hi, I'm new to Quivr, try to install follow the README, but got error, thanks for your help.

I'm uncertain about the `NEXT_PUBLIC_JUNE_API_KEY` configuration because I can't seem to locate where to acquire it.

Here is the log printout for the installment: 
```
[+] Running 3/1
 ✔ Network quivr_default   Created                                                0.1s 
 ✔ Container backend-core  Created                                                0.0s 
 ✔ Container web           Created                                                0.0s 
Attaching to backend-core, web
web           | yarn run v1.22.19
web           | $ next start
backend-core  | WARNING: Package(s) not found: gpt4all
web           | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
backend-core  | INFO:     Will watch for changes in these directories: ['/code']
backend-core  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend-core  | INFO:     Started reloader process [9] using StatReload
web           | - info Loaded env from /app/.env
backend-core  | Process SpawnProcess-1:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend-core  |     self.run()
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend-core  |     self._target(*self._args, **self._kwargs)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend-core  |     target(sockets=sockets)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend-core  |     return asyncio.run(self.serve(sockets=sockets))
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend-core  |     return runner.run(main)
backend-core  |            ^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend-core  |     return self._loop.run_until_complete(task)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend-core  |     return future.result()
backend-core  |            ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend-core  |     config.load()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend-core  |     self.loaded_app = import_from_string(self.app)
backend-core  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend-core  |     module = importlib.import_module(module_str)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-core  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-core  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-core  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-core  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-core  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-core  |   File "/code/main.py", line 21, in <module>
backend-core  |     from routes.subscription_routes import subscription_router
backend-core  |   File "/code/routes/subscription_routes.py", line 35, in <module>
backend-core  |     subscription_service = SubscriptionInvitationService()
backend-core  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain_subscription/subscription_invitation_service.py", line 10, in __init__
backend-core  |     self.supabase_client = get_supabase_client()
backend-core  |                            ^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/settings.py", line 30, in get_supabase_client
backend-core  |     supabase_client: Client = create_client(
backend-core  |                               ^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/supabase/client.py", line 248, in create_client
backend-core  |     return Client(supabase_url=supabase_url, supabase_key=supabase_key, options=options)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/supabase/client.py", line 51, in __init__
backend-core  |     raise SupabaseException("Invalid URL")
backend-core  | supabase.client.SupabaseException: Invalid URL
```

**Comment by mamadoudicko** [comment]
Hi @heywalter 

`NEXT_PUBLIC_JUNE_API_KEY` is not required

However, the problem seems to be related to your `SUPABASE_URL` in `backend/.env`

**Comment by Dadadahhhhh** [comment]
in Debian, the one package I was missing is the one that interacts with my supabase_url postgresql://postgres:postgres@localhost:54322/postgres

once I installed it, I was able to pass this (now getting a different error but for something else so wont post it here)

https://www.postgresql.org/download/linux/debian/
