### ISSUE TITLE
When upload a pdf file got a timeout error

### ISSUE THREAD

**Issue by dheerapat** [StanGirard/quivr#95]
I got this error msg when try to upload a second pdf file (first file is successfully uploaded)
```
2023-05-21 12:15:34 INFO:     172.18.0.1:47508 - "POST /upload HTTP/1.1" 500 Internal Server Error
2023-05-21 12:15:34 ERROR:    Exception in ASGI application
2023-05-21 12:15:34 Traceback (most recent call last):
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2023-05-21 12:15:34     yield
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 38, in write
2023-05-21 12:15:34     n = self._sock.send(buffer)
2023-05-21 12:15:34         ^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/ssl.py", line 1210, in send
2023-05-21 12:15:34     return self._sslobj.write(data)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34 TimeoutError: The write operation timed out
2023-05-21 12:15:34 
2023-05-21 12:15:34 During handling of the above exception, another exception occurred:
2023-05-21 12:15:34 
2023-05-21 12:15:34 Traceback (most recent call last):
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2023-05-21 12:15:34     yield
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
2023-05-21 12:15:34     resp = self._pool.handle_request(req)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
2023-05-21 12:15:34     raise exc
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
2023-05-21 12:15:34     response = connection.handle_request(request)
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 90, in handle_request
2023-05-21 12:15:34     return self._connection.handle_request(request)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 112, in handle_request
2023-05-21 12:15:34     raise exc
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 82, in handle_request
2023-05-21 12:15:34     self._send_request_body(**kwargs)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 135, in _send_request_body
2023-05-21 12:15:34     self._send_event(event, timeout=timeout)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 144, in _send_event
2023-05-21 12:15:34     self._network_stream.write(bytes_to_send, timeout=timeout)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 35, in write
2023-05-21 12:15:34     with map_exceptions(exc_map):
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2023-05-21 12:15:34     self.gen.throw(typ, value, traceback)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2023-05-21 12:15:34     raise to_exc(exc)
2023-05-21 12:15:34 httpcore.WriteTimeout: The write operation timed out
2023-05-21 12:15:34 
2023-05-21 12:15:34 The above exception was the direct cause of the following exception:
2023-05-21 12:15:34 
2023-05-21 12:15:34 Traceback (most recent call last):
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-21 12:15:34     result = await app(  # type: ignore[func-returns-value]
2023-05-21 12:15:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-21 12:15:34     return await self.app(scope, receive, send)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-21 12:15:34     await super().__call__(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-05-21 12:15:34     await self.middleware_stack(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-21 12:15:34     raise exc
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-21 12:15:34     await self.app(scope, receive, _send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2023-05-21 12:15:34     await self.simple_response(scope, receive, send, request_headers=headers)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2023-05-21 12:15:34     await self.app(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-21 12:15:34     raise exc
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-21 12:15:34     await self.app(scope, receive, sender)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-21 12:15:34     raise e
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-21 12:15:34     await self.app(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-05-21 12:15:34     await route.handle(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-05-21 12:15:34     await self.app(scope, receive, send)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-05-21 12:15:34     response = await func(request)
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2023-05-21 12:15:34     raw_response = await run_endpoint_function(
2023-05-21 12:15:34                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-21 12:15:34     return await dependant.call(**values)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/code/api.py", line 103, in upload_file
2023-05-21 12:15:34     message = await filter_file(file, supabase, vector_store, stats_db=None)
2023-05-21 12:15:34               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/code/api.py", line 96, in filter_file
2023-05-21 12:15:34     await file_processors[file_extension](vector_store, file, stats_db=None)
2023-05-21 12:15:34   File "/code/parsers/common.py", line 43, in process_file
2023-05-21 12:15:34     vector_store.add_documents(docs_with_metadata)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 62, in add_documents
2023-05-21 12:15:34     return self.add_texts(texts, metadatas, **kwargs)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/supabase.py", line 78, in add_texts
2023-05-21 12:15:34     return self.add_vectors(vectors, docs)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/supabase.py", line 113, in add_vectors
2023-05-21 12:15:34     return self._add_vectors(self._client, self.table_name, vectors, documents)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/supabase.py", line 222, in _add_vectors
2023-05-21 12:15:34     result = client.from_(table_name).insert(chunk).execute()  # type: ignore
2023-05-21 12:15:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 55, in execute
2023-05-21 12:15:34     r = self.session.request(
2023-05-21 12:15:34         ^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 821, in request
2023-05-21 12:15:34     return self.send(request, auth=auth, follow_redirects=follow_redirects)
2023-05-21 12:15:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 908, in send
2023-05-21 12:15:34     response = self._send_handling_auth(
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 936, in _send_handling_auth
2023-05-21 12:15:34     response = self._send_handling_redirects(
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
2023-05-21 12:15:34     response = self._send_single_request(request)
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1009, in _send_single_request
2023-05-21 12:15:34     response = transport.handle_request(request)
2023-05-21 12:15:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
2023-05-21 12:15:34     with map_httpcore_exceptions():
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2023-05-21 12:15:34     self.gen.throw(typ, value, traceback)
2023-05-21 12:15:34   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2023-05-21 12:15:34     raise mapped_exc(message) from exc
2023-05-21 12:15:34 httpx.WriteTimeout: The write operation timed out
```
not sure what went wrong. will start investigate after this.

**Comment by StanGirard** [comment]
Can you try again ? 👍 new fix

**Comment by dheerapat** [comment]
well after pulling a new fix I got an error right at the beginning when try to build a new image
```
ERROR [4/5] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
```
this is the error I got.

**Comment by StanGirard** [comment]
Weird :/ Can you show more ? 

Also your second pdf might need to be a well configured pdfs and might need OpenCV features

**Comment by dheerapat** [comment]
here is the full docker compose error when trying to build a new image, I deleted everything and cloned fresh repo

```
 => [3/5] COPY ./requirements.txt /code/requirements.txt                                                                                                                                        0.0s
 => ERROR [4/5] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt                                                                                                            662.8s
------                                                                                                                                                                                               
 > [4/5] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt:                                                                                                                         
#0 1.716 Collecting langchain==0.0.166                                                                                                                                                               
#0 2.032   Downloading langchain-0.0.166-py3-none-any.whl (803 kB)                                                                                                                                   
#0 11.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.5/803.5 kB 83.9 kB/s eta 0:00:00                                                                                                            
#0 11.60 Collecting Markdown==3.4.3                                                                                                                                                                  
#0 11.65   Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
#0 11.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 426.1 kB/s eta 0:00:00
#0 11.99 Collecting openai==0.27.6
#0 12.10   Downloading openai-0.27.6-py3-none-any.whl (71 kB)
#0 12.23      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 496.2 kB/s eta 0:00:00
#0 12.63 Collecting pdf2image==1.16.3
#0 12.68   Downloading pdf2image-1.16.3-py3-none-any.whl (11 kB)
#0 12.84 Collecting pypdf==3.8.1
#0 12.90   Downloading pypdf-3.8.1-py3-none-any.whl (248 kB)
#0 13.46      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.8/248.8 kB 445.6 kB/s eta 0:00:00
#0 13.58 Collecting streamlit==1.22.0
#0 13.62   Downloading streamlit-1.22.0-py2.py3-none-any.whl (8.9 MB)
#0 154.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 18.1 kB/s eta 0:00:00
#0 154.5 Collecting StrEnum==0.4.10
#0 154.6   Downloading StrEnum-0.4.10-py3-none-any.whl (7.7 kB)
#0 155.0 Collecting supabase==1.0.3
#0 155.1   Downloading supabase-1.0.3-py3-none-any.whl (11 kB)
#0 155.4 Collecting tiktoken==0.4.0
#0 155.5   Downloading tiktoken-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
#0 188.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.3 kB/s eta 0:00:00
#0 188.6 Collecting unstructured==0.6.5
#0 188.9   Downloading unstructured-0.6.5-py3-none-any.whl (1.3 MB)
#0 221.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.9 kB/s eta 0:00:00
#0 221.5 Collecting anthropic==0.2.8
#0 221.9   Downloading anthropic-0.2.8-py3-none-any.whl (6.3 kB)
#0 222.1 Collecting fastapi==0.95.2
#0 222.1   Downloading fastapi-0.95.2-py3-none-any.whl (56 kB)
#0 222.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 154.0 kB/s eta 0:00:00
#0 222.6 Collecting python-multipart==0.0.6
#0 223.3   Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
#0 231.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 5.4 kB/s eta 0:00:00
#0 232.6 Collecting uvicorn==0.22.0
#0 232.7   Downloading uvicorn-0.22.0-py3-none-any.whl (58 kB)
#0 237.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 12.9 kB/s eta 0:00:00
#0 237.9 Collecting pypandoc==1.11
#0 238.0   Downloading pypandoc-1.11-py3-none-any.whl (20 kB)
#0 240.5 Collecting docx2txt==0.8
#0 240.9   Downloading docx2txt-0.8.tar.gz (2.8 kB)
#0 241.0   Preparing metadata (setup.py): started
#0 241.4   Preparing metadata (setup.py): finished with status 'done'
#0 242.5 Collecting PyYAML>=5.4.1
#0 242.6   Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
#0 256.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 58.7 kB/s eta 0:00:00
#0 258.7 Collecting SQLAlchemy<3,>=1.4
#0 258.8   Downloading SQLAlchemy-2.0.15-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
#0 284.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 108.8 kB/s eta 0:00:00
#0 286.6 Collecting aiohttp<4.0.0,>=3.8.3
#0 286.7   Downloading aiohttp-3.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
#0 290.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 247.2 kB/s eta 0:00:00
#0 291.3 Collecting dataclasses-json<0.6.0,>=0.5.7
#0 291.4   Downloading dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
#0 291.8 Collecting numexpr<3.0.0,>=2.8.4
#0 291.9   Downloading numexpr-2.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (383 kB)
#0 300.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.5/383.5 kB 45.1 kB/s eta 0:00:00
#0 303.6 Collecting numpy<2,>=1
#0 303.7   Downloading numpy-1.24.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#0 656.5      ━━━━━━━━━━━━━                            5.8/17.3 MB 10.7 kB/s eta 0:17:54
#0 656.5 ERROR: Exception:
#0 656.5 Traceback (most recent call last):
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
#0 656.5     yield
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
#0 656.5     data = self._fp_read(amt) if not fp_closed else b""
#0 656.5            ^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
#0 656.5     return self._fp.read(amt) if amt is not None else self._fp.read()
#0 656.5            ^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/http/client.py", line 466, in read
#0 656.5     s = self.fp.read(amt)
#0 656.5         ^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
#0 656.5     return self._sock.recv_into(b)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/ssl.py", line 1278, in recv_into
#0 656.5     return self.read(nbytes, buffer)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/ssl.py", line 1134, in read
#0 656.5     return self._sslobj.read(len, buffer)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5 TimeoutError: The read operation timed out
#0 656.5 
#0 656.5 During handling of the above exception, another exception occurred:
#0 656.5 
#0 656.5 Traceback (most recent call last):
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
#0 656.5     status = run_func(*args)
#0 656.5              ^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
#0 656.5     return func(self, options, args)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 400, in run
#0 656.5     requirement_set = resolver.resolve(
#0 656.5                       ^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
#0 656.5     result = self._result = resolver.resolve(
#0 656.5                             ^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#0 656.5     state = resolution.resolve(requirements, max_rounds=max_rounds)
#0 656.5             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
#0 656.5     failure_causes = self._attempt_to_pin_criterion(name)
#0 656.5                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
#0 656.5     criteria = self._get_updated_criteria(candidate)
#0 656.5                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
#0 656.5     self._add_to_criteria(criteria, requirement, parent=candidate)
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#0 656.5     if not criterion.candidates:
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#0 656.5     return bool(self._sequence)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#0 656.5     return any(self)
#0 656.5            ^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#0 656.5     return (c for c in iterator if id(c) not in self._incompatible_ids)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#0 656.5     candidate = func()
#0 656.5                 ^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#0 656.5     self._link_candidate_cache[link] = LinkCandidate(
#0 656.5                                        ^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
#0 656.5     super().__init__(
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
#0 656.5     self.dist = self._prepare()
#0 656.5                 ^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
#0 656.5     dist = self._prepare_distribution()
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
#0 656.5     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
#0 656.5     return self._prepare_linked_requirement(req, parallel_builds)
#0 656.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
#0 656.5     local_file = unpack_url(
#0 656.5                  ^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
#0 656.5     file = get_http_url(
#0 656.5            ^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
#0 656.5     from_path, content_type = download(link, temp_dir.path)
#0 656.5                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 656.5   File "/usr/local/lib/python3.11/site-packages/pip/_internal/network/download.py", line 147, in __call__
[+] Building 667.5s (9/10)                                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                                            0.0s
 => => transferring dockerfile: 545B                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                                                               3.0s
 => [1/6] FROM docker.io/library/node:18-alpine@sha256:1ccc70acda680aa4ba47f53e7c40b2d4d6892de74817128e0662d32647dd7f4d                                                                         0.0s
 => [internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 506.48kB                                                                                                                                                           0.0s
 => CACHED [2/6] RUN mkdir -p /app                                                                                                                                                              0.0s
 => CACHED [3/6] WORKDIR /app                                                                                                                                                                   0.0s
 => CACHED [4/6] COPY package*.json /app/                                                                                                                                                       0.0s
 => CANCELED [5/6] RUN yarn install                                                                                                                                                           664.4s
failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade -r /code/requirements.txt" did not complete successfully: exit code: 2 
```

**Comment by StanGirard** [comment]
So weird. Did you pull the latest version ?

**Comment by dheerapat** [comment]
Ok, after some tweaking I finally build a docker images with the new fix and voila! my pdf file is now uploaded successfully. I will close this issue and pull request my tweak on Dockerfile in case someone encounter this same error.

**Comment by StanGirard** [comment]
Cant wait :)
