### ISSUE TITLE
No module named 'docx2txt'

### ISSUE THREAD

**Issue by hey-lee** [StanGirard/quivr#97]
When I upload a `.docx` file

```log
fa2e3edd7aa1_backend | INFO:     172.20.0.1:64212 - "POST /upload HTTP/1.1" 500 Internal Server Error
fa2e3edd7aa1_backend | ERROR:    Exception in ASGI application
fa2e3edd7aa1_backend | Traceback (most recent call last):
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
fa2e3edd7aa1_backend |     result = await app(  # type: ignore[func-returns-value]
fa2e3edd7aa1_backend |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fa2e3edd7aa1_backend |     return await self.app(scope, receive, send)
fa2e3edd7aa1_backend |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
fa2e3edd7aa1_backend |     await super().__call__(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
fa2e3edd7aa1_backend |     await self.middleware_stack(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
fa2e3edd7aa1_backend |     raise exc
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
fa2e3edd7aa1_backend |     await self.app(scope, receive, _send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
fa2e3edd7aa1_backend |     await self.simple_response(scope, receive, send, request_headers=headers)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
fa2e3edd7aa1_backend |     await self.app(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
fa2e3edd7aa1_backend |     raise exc
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
fa2e3edd7aa1_backend |     await self.app(scope, receive, sender)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
fa2e3edd7aa1_backend |     raise e
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
fa2e3edd7aa1_backend |     await self.app(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
fa2e3edd7aa1_backend |     await route.handle(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
fa2e3edd7aa1_backend |     await self.app(scope, receive, send)
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
fa2e3edd7aa1_backend |     response = await func(request)
fa2e3edd7aa1_backend |                ^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
fa2e3edd7aa1_backend |     raw_response = await run_endpoint_function(
fa2e3edd7aa1_backend |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
fa2e3edd7aa1_backend |     return await dependant.call(**values)
fa2e3edd7aa1_backend |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/code/api.py", line 103, in upload_file
fa2e3edd7aa1_backend |     message = await filter_file(file, supabase, vector_store, stats_db=None)
fa2e3edd7aa1_backend |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/code/api.py", line 96, in filter_file
fa2e3edd7aa1_backend |     await file_processors[file_extension](vector_store, file, stats_db=None)
fa2e3edd7aa1_backend |   File "/code/parsers/common.py", line 27, in process_file
fa2e3edd7aa1_backend |     documents = loader.load()
fa2e3edd7aa1_backend |                 ^^^^^^^^^^^^^
fa2e3edd7aa1_backend |   File "/usr/local/lib/python3.11/site-packages/langchain/document_loaders/word_document.py", line 51, in load
fa2e3edd7aa1_backend |     import docx2txt
fa2e3edd7aa1_backend | ModuleNotFoundError: No module named 'docx2txt'
```

**Comment by StanGirard** [comment]
Fixed
