### ISSUE TITLE
[Issue] 500 error when submitting a chat request

### ISSUE THREAD

**Issue by thehunmonkgroup** [StanGirard/quivr#981]
## Submitting a Bug Report 🐛

Getting this when submitting a chat:

```
backend-chat     | 2023-08-18 21:02:34,928 [INFO] repository.chat.create_chat: New chat entry in chats table for user 1c6d623c-8de1-4f11-a434-151200ca4bd8
backend-chat     | 2023-08-18 21:02:35,174 [INFO] repository.chat.create_chat: Insert response [{'chat_id': '5f067df3-dc3d-4e8a-b159-fbe0bc721e3a', 'user_id': '1c6d623c-8de1-4f11-a434-151200ca4bd8', 'creation_time': '2023-08-18T21:02:35.117387', 'history': None, 'chat_name': 'who is the'}]
backend-chat     | INFO:     172.18.0.6:46434 - "POST /chat HTTP/1.1" 200 OK
backend-chat     | INFO:     172.18.0.6:46434 - "OPTIONS /chat/5f067df3-dc3d-4e8a-b159-fbe0bc721e3a/question/stream?brain_id=ebb8f6b2-c74d-41fb-a342-79a8746a7ef4 HTTP/1.1" 200 OK
backend-chat     | 2023-08-18 21:02:35,824:INFO - Streaming request for gpt-3.5-turbo
backend-chat     | 2023-08-18 21:02:36,073 [INFO] models.users: User chad@apartmentlines.com request count updated to 1
backend-chat     | INFO:     172.18.0.6:46434 - "POST /chat/5f067df3-dc3d-4e8a-b159-fbe0bc721e3a/question/stream?brain_id=ebb8f6b2-c74d-41fb-a342-79a8746a7ef4 HTTP/1.1" 500 Internal Server Error
backend-chat     | ERROR:    Exception in ASGI application
backend-chat     | Traceback (most recent call last):
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-chat     |     result = await app(  # type: ignore[func-returns-value]
backend-chat     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-chat     |     return await self.app(scope, receive, send)
backend-chat     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-chat     |     await super().__call__(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-chat     |     await self.middleware_stack(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-chat     |     raise exc
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-chat     |     await self.app(scope, receive, _send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-chat     |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-chat     |     await self.app(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-chat     |     raise exc
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-chat     |     await self.app(scope, receive, sender)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-chat     |     raise e
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-chat     |     await self.app(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-chat     |     await route.handle(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-chat     |     await self.app(scope, receive, send)
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-chat     |     response = await func(request)
backend-chat     |                ^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-chat     |     raw_response = await run_endpoint_function(
backend-chat     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-chat     |     return await dependant.call(**values)
backend-chat     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/code/routes/chat_routes.py", line 269, in create_stream_question_handler
backend-chat     |     gpt_answer_generator = OpenAIBrainPicking(
backend-chat     |                            ^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/code/llm/openai.py", line 31, in __init__
backend-chat     |     super().__init__(
backend-chat     |   File "/code/llm/qa_base.py", line 59, in __init__
backend-chat     |     super().__init__(
backend-chat     |   File "/code/llm/base.py", line 55, in __init__
backend-chat     |     super().__init__(**data)
backend-chat     |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-chat     | pydantic.error_wrappers.ValidationError: 4 validation errors for OpenAIBrainPicking
backend-chat     | supabase_client
backend-chat     |   field required (type=value_error.missing)
backend-chat     | vector_store
backend-chat     |   field required (type=value_error.missing)
backend-chat     | qa
backend-chat     |   field required (type=value_error.missing)
backend-chat     | embeddings
backend-chat     |   field required (type=value_error.missing)
```

Successfully added embeddings to a brain, but I get this every time I try to ask a question.

Given it's a Pydantic validation error, this seems like a code bug. I see those attributes defined on `QABaseBrainPicking` class, `supabase_client` and `vector_store` are instantiated there without error.

**Comment by BrewingCodeAndColdOnes** [comment]
+1 here

**Comment by antoinesco** [comment]
I have the same issue.

**Comment by wholydrops** [comment]
Any fix on this so far @thehunmonkgroup

**Comment by thehunmonkgroup** [comment]
It's not something I'm willing to dig into, too many other open source projects already in the air :)

**Comment by antoinesco** [comment]
I managed to fix it, but reinstalling docker, and recreating the project, and tables in supabase.
Be sure that Traefik is running properly.

**Comment by tsadigovAgmail** [comment]
> It's not something I'm willing to dig into, too many other open source projects already in the air :)

Which are they, any one that worth mentioning?

**Comment by thehunmonkgroup** [comment]
@tsadigovAgmail in the LLM world, just https://github.com/llm-workflow-engine/llm-workflow-engine

**Comment by mamadoudicko** [comment]
This issue has been resolve [here](https://github.com/StanGirard/quivr/pull/975/commits/14cdfe203da6293af30b459b0d6e5b6344f06891). Please get last version from main
